document.addEventListener('DOMContentLoaded', () => {
  const demoButtons = document.querySelectorAll('[data-demo-message]');
  if (demoButtons.length) {

  const toast = document.createElement('div');
  toast.className = 'toast';
  toast.setAttribute('role', 'status');
  toast.setAttribute('aria-live', 'polite');
  toast.hidden = true;
  document.body.appendChild(toast);

  let timer;
  demoButtons.forEach((button) => {
    button.addEventListener('click', () => {
      clearTimeout(timer);
      toast.textContent = button.dataset.demoMessage;
      toast.hidden = false;
      timer = setTimeout(() => { toast.hidden = true; }, 3800);
    });
  }); }

  const quickCheck = document.querySelector('[data-single-question]');
  if (quickCheck) quickCheck.addEventListener('submit', (event) => {
    event.preventDefault(); const value = new FormData(quickCheck).get('check');
    const correct = quickCheck.dataset.correct || 'b';
    quickCheck.querySelector('.inline-feedback').textContent = !value ? 'Selecciona una alternativa antes de revisar.' : value === correct ? (quickCheck.dataset.success || '¡Correcto! Aplicaste el criterio central de esta unidad.') : (quickCheck.dataset.retry || 'Aún no. Vuelve a comparar las características de cada enfoque.');
  });

  const quiz = document.querySelector('#ecep-quiz'); if (!quiz) return;
  const questionSets = { bio: [
    ['Comprensión conceptual','¿Qué distingue al modelo biopsicosocial?',['Explica el desempeño solo desde el diagnóstico.','Comprende el funcionamiento como interacción entre factores individuales y contextuales.','Considera que todos requieren los mismos apoyos.','Reemplaza la observación pedagógica por información clínica.'],1],
    ['Comprensión conceptual','¿Cuál afirmación es coherente con este modelo?',['Las características individuales dejan de ser relevantes.','Toda dificultad se origina en el ambiente.','Una característica puede expresarse distinto según las condiciones de participación.','Los apoyos dependen solo del diagnóstico.'],2],
    ['Interpretación','Una estudiante participa más cuando anticipa la rutina con imágenes. ¿Qué permite interpretar?',['La respuesta depende también de los apoyos disponibles.','No necesita nuevos desafíos.','La dificultad desapareció definitivamente.','Las imágenes deben reemplazar toda instrucción oral.'],0],
    ['Interpretación','Un informe dice “no completa tareas porque presenta DEA”. ¿Qué falta?',['Una calificación más baja.','Información sobre contexto, demandas y apoyos usados.','Confirmar que la dificultad es permanente.','Comparar solo con el promedio.'],1],
    ['Aplicación','Valentina responde mejor a instrucciones orales y visuales. ¿Qué acción es coherente?',['Mantener solo instrucciones escritas.','Reducir todos los objetivos.','Combinar formatos y observar qué favorece autonomía y comprensión.','Separarla del trabajo grupal.'],2],
    ['Aplicación','Un estudiante resuelve con material concreto, pero se bloquea ante símbolos. ¿Qué harías?',['Concluir que no comprende matemática.','Planificar una transición entre representaciones y registrar su respuesta.','Eliminar los problemas.','Repetir ejercicios sin cambios.'],1],
    ['Aplicación','Una estudiante aporta por escrito, pero no habla en debates. ¿Qué análisis es más completo?',['No tiene ideas.','Solo es timidez.','Explorar factores personales, dinámica grupal y alternativas de comunicación.','Evaluar solo oralmente.'],2],
    ['Decisión pedagógica','Ante baja participación, ¿qué decisión refleja mejor el modelo?',['Asignar una etiqueta y mantener la planificación.','Cambiar todas las metas sin evidencia.','Ofrecer apoyos, observar la respuesta y ajustar la enseñanza.','Esperar que se adapte sola.'],2]
  ], evolution: [
    ['Comprensión conceptual','¿Qué caracteriza al enfoque homogeneizador?',['Reconoce múltiples formas de aprender.','Espera que el grupo avance de una manera uniforme.','Elimina las barreras del entorno.','Prioriza la participación en el aula común.'],1],
    ['Comprensión conceptual','¿Qué cambio representa el enfoque inclusivo?',['Traslada al estudiante a un espacio separado.','Busca que la persona se adapte sin modificar la escuela.','Transforma culturas, políticas y prácticas para responder a la diversidad.','Clasifica para enseñar según el déficit.'],2],
    ['Interpretación','Una escuela agrupa permanentemente al alumnado según diagnóstico y ofrece un currículo reducido. ¿Qué enfoque predomina?',['Déficit y categorización.','Inclusión.','Diversidad.','Diseño universal.'],0],
    ['Interpretación','Un estudiante asiste al aula común, pero debe realizar exactamente las mismas tareas sin apoyos. ¿Qué tensión se observa?',['Participación plena.','Presencia física sin transformación de las condiciones.','Eliminación de barreras.','Diversificación de la enseñanza.'],1],
    ['Aplicación','Un equipo afirma que Emilia debe “estar preparada” antes de participar con su curso. ¿Qué revisión corresponde?',['Mantenerla fuera hasta que alcance el promedio.','Preguntar qué apoyos y cambios permitirían su participación ahora.','Reducir sus oportunidades de interacción.','Aplicar una prueba para justificar la separación.'],1],
    ['Aplicación','La clase contempla distintas formas de acceder, participar y demostrar lo aprendido. ¿Qué enfoque expresa mejor?',['Homogeneizador.','Déficit.','Normalización entendida como asimilación.','Diversidad e inclusión.'],3],
    ['Aplicación','Un profesor detecta que una actividad excluye a quienes requieren más tiempo. ¿Qué acción refleja evolución hacia la inclusión?',['Atribuir el problema a los estudiantes.','Ofrecer tiempo flexible y revisar la demanda de la tarea.','Retirar a quienes no terminan.','Mantener la actividad para asegurar igualdad.'],1],
    ['Decisión pedagógica','¿Qué decisión es más coherente con una educación inclusiva?',['Diseñar primero para un estudiante promedio y adaptar al final.','Separar apoyos de la planificación del curso.','Planificar desde la diversidad y ajustar apoyos según evidencias de participación.','Usar el diagnóstico como único criterio para decidir.'],2]
  ], inclusion: [
    ['Comprensión conceptual','¿Qué es una barrera para el aprendizaje y la participación?',['Una condición fija del estudiante.','Una dificultad que surge de la interacción con condiciones del contexto.','Un diagnóstico que determina el rendimiento.','Una conducta que debe corregirse antes de participar.'],1],
    ['Comprensión conceptual','¿Qué describe mejor una necesidad de apoyo?',['Una etiqueta permanente.','Una razón para reducir siempre los objetivos.','El apoyo requerido para acceder, aprender o participar en una situación.','Una característica exclusiva de estudiantes con diagnóstico.'],2],
    ['Interpretación','La plataforma de lectura no admite lector de pantalla. ¿Dónde se ubica principalmente la barrera?',['En la capacidad del estudiante.','En el recurso tecnológico y su diseño.','En la familia.','En el objetivo de aprendizaje.'],1],
    ['Interpretación','Una familia migrante no comprende las comunicaciones escolares porque solo se envían con lenguaje técnico. ¿Qué análisis corresponde?',['Falta de interés familiar.','Una barrera comunicacional y cultural que la escuela puede modificar.','Una necesidad de diagnóstico.','Un problema ajeno a la enseñanza.'],1],
    ['Aplicación','Algunos estudiantes requieren más tiempo para organizar una respuesta escrita. ¿Qué estrategia diversificada es pertinente?',['Bajar la expectativa de aprendizaje.','Ofrecer tiempo flexible y apoyos para planificar, manteniendo el objetivo.','Excluir la producción escrita.','Evaluar solamente rapidez.'],1],
    ['Aplicación','En una actividad oral, una estudiante comunica mejor sus ideas mediante imágenes y palabras clave. ¿Qué harías?',['Aceptar distintas formas de expresión alineadas con el objetivo.','Exigir solo exposición oral.','Reemplazar el objetivo por uno más fácil.','Pedir que observe sin participar.'],0],
    ['Aplicación','El curso estudia relatos de distintas comunidades. ¿Qué acción fortalece inclusión y multiculturalidad?',['Presentar una cultura como norma.','Evitar diferencias para prevenir conflictos.','Incorporar voces diversas y revisar estereotipos con participación del grupo.','Asignar a estudiantes migrantes la tarea de representar a toda su cultura.'],2],
    ['Decisión pedagógica','Ante baja participación de varios estudiantes, ¿qué debería hacer primero el equipo?',['Derivarlos individualmente.','Revisar las barreras de la actividad, recoger sus perspectivas y diversificar apoyos.','Mantener la actividad para comparar resultados.','Reducir el currículo del grupo.'],1]
  ], regulations: [
    ['Comprensión conceptual','¿Qué instrumento reconoce el derecho a un sistema de educación inclusivo en todos los niveles?',['Decreto 170.','Convención sobre los Derechos de las Personas con Discapacidad.','Decreto 67.','Reglamento interno.'],1],
    ['Comprensión conceptual','¿Cuál es el propósito central del Decreto 170?',['Regular toda evaluación escolar.','Fijar criterios para identificar estudiantes con NEE beneficiarios de subvención de educación especial.','Prohibir la selección escolar.','Definir adecuaciones curriculares.'],1],
    ['Interpretación','Un equipo necesita decidir cómo diversificar y, si es necesario, adecuar el currículo en educación básica. ¿Qué norma es directamente pertinente?',['Decreto 83 de 2015.','Ley 20.845 exclusivamente.','Decreto 170 exclusivamente.','PNCE 2024–2030 exclusivamente.'],0],
    ['Interpretación','Una escuela usa una única prueba y no permite ajustes coherentes con la enseñanza. ¿Qué norma orienta especialmente la evaluación para favorecer el progreso?',['Ley 20.422.','Decreto 67 de 2018.','Ley 20.845.','Convención, artículo sobre accesibilidad física únicamente.'],1],
    ['Aplicación','Antes de decidir una adecuación curricular individual, ¿qué corresponde según el Decreto 83?',['Aplicarla automáticamente por diagnóstico.','Implementar diversificación y evaluar si resulta insuficiente.','Eliminar objetivos básicos.','Esperar una calificación insuficiente.'],1],
    ['Aplicación','Una escuela niega matrícula por discapacidad. ¿Qué marco resulta vulnerado de manera directa?',['Solo su calendario escolar.','Igualdad de oportunidades, no discriminación e inclusión.','Únicamente las reglas de calificación.','Solo la planificación de aula.'],1],
    ['Aplicación','Ante conflictos reiterados, el equipo propone únicamente sanciones. ¿Qué aporta la PNCE 2024–2030?',['Un enfoque formativo, participativo, de cuidado colectivo e inclusión.','Un procedimiento para diagnosticar DEA.','Criterios de promoción anual.','Una tabla de adecuaciones curriculares.'],0],
    ['Decisión pedagógica','¿Cuál uso de la normativa es profesionalmente más adecuado?',['Memorizar números sin analizar la situación.','Aplicar una norma aislada aunque contradiga derechos.','Identificar el derecho o proceso implicado, articular normas pertinentes y justificar la decisión pedagógica.','Usar siempre el Decreto 170 para cualquier necesidad.'],2]
  ], decree83: [
    ['Comprensión conceptual','¿Qué debe ocurrir antes de considerar una adecuación curricular individual?',['Asignar un diagnóstico.','Implementar estrategias diversificadas y evaluar su efecto.','Reducir los objetivos del estudiante.','Separar al estudiante del curso.'],1],
    ['Comprensión conceptual','¿Cuál alternativa corresponde a una adecuación de acceso?',['Graduar la complejidad de un objetivo.','Eliminar un aprendizaje básico imprescindible.','Modificar el formato de presentación o respuesta sin cambiar el objetivo.','Cambiar el nivel educativo del objetivo.'],2],
    ['Interpretación','Una estudiante demuestra el mismo aprendizaje usando teclado en vez de escritura manual. ¿Qué tipo de decisión es?',['Adecuación de acceso.','Adecuación a un objetivo.','Eliminación de un objetivo.','Promoción automática.'],0],
    ['Interpretación','Tras apoyos diversificados, un estudiante mantiene un desfase significativo y el equipo gradúa la complejidad de un OA. ¿Qué representa?',['Una estrategia general para todo el curso.','Una adecuación curricular a los objetivos de aprendizaje.','Una eximición sin evaluación.','Una adecuación exclusivamente física.'],1],
    ['Aplicación','Un curso presenta dificultades para comprender instrucciones extensas. ¿Cuál es la primera respuesta más coherente?',['Crear de inmediato un plan individual para cada estudiante.','Diversificar las instrucciones con ejemplos, segmentos y apoyos visuales.','Eliminar el objetivo para todo el curso.','Solicitar diagnóstico antes de modificar la clase.'],1],
    ['Aplicación','Un estudiante comprende contenidos, pero no accede a un texto impreso por baja visión. ¿Qué medida mantiene el objetivo?',['Texto ampliado o formato digital accesible.','Eliminar la lectura del currículo.','Sustituir el objetivo por uno de nivel inferior.','Calificar solo la asistencia.'],0],
    ['Aplicación','¿Qué evidencia justifica mejor una adecuación curricular individual?',['La preferencia aislada de un adulto.','El diagnóstico por sí solo.','Evaluación amplia de necesidades y respuesta insuficiente a la diversificación implementada.','Una única calificación baja.'],2],
    ['Decisión pedagógica','¿Qué decisión respeta mejor el Decreto 83?',['Eliminar primero objetivos para evitar frustración.','Usar adecuaciones idénticas para una misma categoría diagnóstica.','Seleccionar el ajuste menos significativo que permita participación y progreso, monitorearlo y revisarlo.','Mantener una adecuación sin evaluar sus resultados.'],2]
  ], integration: [
    ['Comprensión conceptual','¿Qué idea resume mejor el modelo biopsicosocial?',['La dificultad pertenece exclusivamente al estudiante.','El funcionamiento surge de la interacción entre características personales y contexto.','El contexto explica por sí solo todo desempeño.','El diagnóstico determina la respuesta educativa.'],1,'Unidad 1'],
    ['Interpretación','Una estudiante mejora al recibir anticipación visual. ¿Qué interpretación es más completa?',['La respuesta evidencia interacción entre sus características y el apoyo.','La dificultad desapareció.','Solo necesita imágenes.','El objetivo debe reducirse.'],0,'Unidad 1'],
    ['Decisión pedagógica','¿Qué harías ante un desempeño que cambia según el formato de instrucción?',['Mantener un único formato.','Observar condiciones, diversificar apoyos y evaluar la respuesta.','Derivar antes de modificar.','Calificar el déficit.'],1,'Unidad 1'],
    ['Comprensión conceptual','¿Qué distingue inclusión de integración asimilacionista?',['La inclusión exige que el estudiante se adapte.','La inclusión transforma condiciones para asegurar participación y aprendizaje.','La integración siempre elimina barreras.','No existe diferencia pedagógica.'],1,'Unidad 2'],
    ['Interpretación','Un estudiante está en aula común, pero sin apoyos y con exigencia uniforme. ¿Qué refleja?',['Inclusión plena.','Presencia física sin transformación suficiente.','Diversificación universal.','Adecuación de acceso.'],1,'Unidad 2'],
    ['Aplicación','¿Qué acción expresa evolución hacia un enfoque inclusivo?',['Agrupar permanentemente por diagnóstico.','Diseñar desde la diversidad y revisar barreras.','Esperar preparación previa para participar.','Reducir expectativas por categoría.'],1,'Unidad 2'],
    ['Comprensión conceptual','¿Qué es una barrera para el aprendizaje y la participación?',['Una condición fija individual.','Una dificultad producida en la interacción con condiciones del contexto.','Un sinónimo de diagnóstico.','Una falta de esfuerzo.'],1,'Unidad 3'],
    ['Interpretación','Una comunicación técnica excluye a familias que no dominan ese registro. ¿Qué barrera predomina?',['Comunicacional y cultural.','Motora.','Diagnóstica.','Curricular individual.'],0,'Unidad 3'],
    ['Aplicación','¿Qué respuesta conserva el objetivo y amplía la participación?',['Una única forma de demostrar aprendizaje.','Alternativas de expresión alineadas con el propósito.','Eliminar el contenido complejo.','Separar a quienes requieren apoyo.'],1,'Unidad 3'],
    ['Comprensión conceptual','¿Qué norma regula especialmente evaluación, calificación y promoción?',['Decreto 170.','Decreto 67 de 2018.','Ley 20.845.','PNCE 2024–2030.'],1,'Unidad 4'],
    ['Interpretación','¿Qué norma consulta directamente un equipo para identificar beneficiarios de subvención de educación especial?',['Decreto 170.','Decreto 83 de 2015.','Decreto 67.','Ley 20.845.'],0,'Unidad 4'],
    ['Decisión pedagógica','¿Cómo debe usarse la normativa ante un caso complejo?',['Elegir un número de memoria.','Articular derechos, norma específica y evidencia pedagógica.','Aplicar siempre una sola norma.','Priorizar procedimientos sobre derechos.'],1,'Unidad 4'],
    ['Comprensión conceptual','¿Cuál es la secuencia correcta del Decreto 83?',['Adecuar, diagnosticar y luego diversificar.','Diversificar, evaluar la respuesta y adecuar si es necesario.','Eliminar objetivos y observar.','Calificar y luego apoyar.'],1,'Unidad 5'],
    ['Interpretación','Usar teclado manteniendo el objetivo de producción escrita corresponde a:',['Adecuación de acceso.','Eliminación del objetivo.','Promoción especial.','Adecuación por temporalización.'],0,'Unidad 5'],
    ['Aplicación','¿Qué sustenta una adecuación a los OA?',['Solo el diagnóstico.','Evaluación amplia, evidencia de apoyos previos insuficientes y monitoreo.','Una preferencia del docente.','Una prueba aislada.'],1,'Unidad 5']
  ], assessment: [
    ['Comprensión conceptual','¿Qué caracteriza una evaluación integral?',['Utiliza una sola prueba estandarizada.','Articula diversas fuentes, profesionales y contextos para orientar apoyos.','Busca únicamente confirmar un diagnóstico.','Se realiza sin participación de la familia.'],1],
    ['Comprensión conceptual','¿Cuál es su propósito educativo central?',['Clasificar al estudiante.','Justificar una calificación.','Identificar fortalezas, necesidades de apoyo y una respuesta educativa pertinente.','Comparar exclusivamente con el promedio.'],2],
    ['Interpretación','Un informe contiene puntajes, pero no describe desempeño en aula, contexto ni apoyos probados. ¿Qué falta?',['Más etiquetas clínicas.','Una comprensión contextual y funcional del aprendizaje.','Eliminar la entrevista familiar.','Una calificación final.'],1],
    ['Interpretación','La familia informa que el estudiante resuelve tareas cotidianas que no logra mostrar en una prueba. ¿Cómo usar ese antecedente?',['Descartarlo por no ser escolar.','Integrarlo como evidencia relevante y contrastarlo con otras fuentes.','Reemplazar toda evaluación profesional.','Usarlo solo si confirma el déficit.'],1],
    ['Aplicación','¿Qué conjunto entrega evidencia más completa?',['Una prueba aislada.','Observación, producciones, entrevistas, evaluación curricular y antecedentes pertinentes.','Solo promedio de notas.','Solo diagnóstico médico.'],1],
    ['Aplicación','Un estudiante progresa al recibir apoyos visuales. ¿Qué debe registrar el equipo?',['Solo que respondió bien.','Condiciones, tipo de apoyo, nivel de autonomía y cambios en participación y aprendizaje.','Únicamente la fecha.','La categoría diagnóstica.'],1],
    ['Aplicación','¿Cómo deben comunicarse los resultados a la familia?',['Con tecnicismos y puntajes exclusivamente.','De manera comprensible, incluyendo fortalezas, necesidades, apoyos y acciones del establecimiento.','Solo mediante el diagnóstico.','Sin mencionar el contexto escolar.'],1],
    ['Decisión pedagógica','Tras evaluar, ¿qué decisión es más pertinente?',['Aplicar el mismo apoyo a estudiantes con igual diagnóstico.','Planificar apoyos vinculados con la evidencia, responsables y seguimiento.','Archivar el informe sin modificar la enseñanza.','Esperar la reevaluación para actuar.'],1]
  ], psychoeducational: [
    ['Comprensión conceptual','¿Qué distingue la evaluación curricular de una medición aislada?',['Describe únicamente un puntaje.','Analiza el desempeño respecto del currículo, las tareas y condiciones de enseñanza.','Confirma por sí sola un diagnóstico.','Excluye la observación del aula.'],1],
    ['Comprensión conceptual','¿Qué significa triangular evidencia?',['Repetir tres veces la misma prueba.','Contrastar información de distintas fuentes, métodos y momentos.','Promediar todas las calificaciones.','Elegir el resultado más bajo.'],1],
    ['Interpretación','Un estudiante falla en una prueba descontextualizada, pero aplica la habilidad en tareas de aula con apoyos. ¿Qué corresponde concluir?',['No posee la habilidad.','La evidencia es divergente y deben analizarse las demandas y apoyos antes de concluir.','La prueba debe ignorarse siempre.','Debe reducirse el objetivo.'],1],
    ['Interpretación','Dos tareas evalúan comprensión, pero una exige mucha escritura. El desempeño cambia. ¿Qué variable debe examinarse?',['La demanda de respuesta escrita como posible interferencia.','Solo la motivación.','El diagnóstico médico.','La asistencia anual.'],0],
    ['Aplicación','¿Qué procedimiento es más pertinente para conocer estrategias lectoras?',['Solo registrar velocidad.','Combinar lectura, preguntas, verbalización de estrategias y análisis de errores.','Aplicar una encuesta familiar únicamente.','Revisar la nota final.'],1],
    ['Aplicación','Antes de aplicar un instrumento, el profesional debe verificar principalmente:',['Que sea el más corto.','Su propósito, pertinencia, condiciones de aplicación y límites interpretativos.','Que produzca un diagnóstico.','Que todos obtengan resultados comparables sin ajustes.'],1],
    ['Aplicación','¿Qué redacción interpreta evidencia con mayor rigor?',['No puede aprender fracciones.','En tareas simbólicas sin apoyo comete errores de equivalencia; con representación visual identifica relaciones y explica su estrategia.','Tiene bajo rendimiento general.','Su diagnóstico explica los errores.'],1],
    ['Decisión pedagógica','La evidencia muestra una barrera de formato, no del objetivo. ¿Qué decisión corresponde?',['Modificar inmediatamente el OA.','Ajustar el acceso o la respuesta y volver a recoger evidencia del mismo aprendizaje.','Suspender la evaluación.','Mantener el formato para comparar.'],1]
  ], deaIdentification: [
    ['Comprensión conceptual','¿Qué rasgo es necesario considerar al evaluar una posible DEA?',['Una dificultad aislada en cualquier asignatura.','Dificultad significativa y persistente en lectura, lectura-escritura o matemática pese a medidas pedagógicas pertinentes.','Una calificación insuficiente.','La preferencia por apoyos visuales.'],1],
    ['Comprensión conceptual','¿Por qué es necesario el diagnóstico diferencial?',['Para encontrar más etiquetas.','Para examinar si el desempeño se explica mejor por factores sensoriales, intelectuales, emocionales, ambientales o de enseñanza.','Para reemplazar la evaluación curricular.','Para excluir a la familia.'],1],
    ['Interpretación','Un curso completo presenta bajo desempeño tras meses sin enseñanza sistemática de lectura. ¿Qué interpretación es prioritaria?',['Todos presentan DEA.','Debe revisarse la oportunidad y calidad de enseñanza antes de atribuir dificultades específicas individuales.','Se confirma una dificultad crónica.','Basta una prueba estandarizada.'],1],
    ['Interpretación','Una estudiante mejora rápidamente con enseñanza explícita y práctica guiada. ¿Qué indica esta respuesta?',['Confirma necesariamente DEA.','La dificultad era inmodificable.','La respuesta al apoyo es evidencia relevante que obliga a revisar hipótesis antes de diagnosticar.','Debe suspenderse el apoyo.'],2],
    ['Aplicación','¿Qué antecedente demuestra mejor persistencia?',['Una prueba baja.','Registros longitudinales de progreso bajo medidas pedagógicas pertinentes y monitoreadas.','La opinión aislada de un adulto.','Una ausencia escolar.'],1],
    ['Aplicación','Antes de derivar, el equipo detecta dificultades lectoras. ¿Qué acción corresponde?',['Esperar sin intervenir.','Implementar enseñanza diversificada, apoyo focalizado y monitoreo continuo, documentando la respuesta.','Asignar diagnóstico provisorio.','Reducir los objetivos.'],1],
    ['Aplicación','En la evaluación aparecen dificultades y antecedentes de visión no corregida. ¿Qué procede?',['Ignorar el antecedente.','Concluir DEA por los puntajes.','Asegurar evaluación de salud y analizar cuánto explica el acceso visual antes de concluir.','Aplicar más tareas impresas.'],2],
    ['Decisión pedagógica','¿Cuál decisión es más rigurosa ante evidencia todavía ambigua?',['Confirmar DEA para acceder rápido a recursos.','Mantener apoyos, ampliar evidencia interdisciplinaria y contrastar explicaciones alternativas.','Retirar apoyos hasta tener diagnóstico.','Usar solo el resultado más bajo.'],1]
  ], supportPlanning: [
    ['Comprensión conceptual','¿Qué función cumple un Plan de Apoyo Individual (PAI)?',['Registrar solo el diagnóstico.','Organizar apoyos, responsables y ajustes derivados de la evaluación integral.','Reemplazar la planificación del curso.','Modificar siempre los OA.'],1],
    ['Comprensión conceptual','¿Cuándo forma parte del PAI un PACI?',['Para todo estudiante con apoyo.','Cuando se requieren adecuaciones significativas a los objetivos de aprendizaje.','Ante cualquier ajuste de acceso.','Solo por solicitud familiar.'],1],
    ['Interpretación','Un plan dice “mejorar lectura” sin acción, responsable ni indicador. ¿Cuál es su principal debilidad?',['Tiene demasiada información.','No permite implementar ni evaluar el apoyo.','Debe incluir un diagnóstico nuevo.','Necesita reducir objetivos.'],1],
    ['Interpretación','El apoyo mejora precisión, pero el estudiante sigue dependiendo totalmente del adulto. ¿Qué debe analizarse?',['Solo mantenerlo.','Eficacia y también autonomía, intensidad y posibilidad de retirar ayudas gradualmente.','Cambiar el diagnóstico.','Aumentar todas las ayudas.'],1],
    ['Aplicación','¿Cuál objetivo de apoyo es más observable?',['Fortalecer comprensión.','En ocho semanas, identificará ideas centrales usando organizador visual con ayuda gradualmente decreciente en 4 de 5 textos.','Mejorar mucho.','Trabajar lectura semanalmente.'],1],
    ['Aplicación','¿Qué indicador informa mejor sobre participación?',['Cantidad de sesiones realizadas.','Frecuencia y autonomía con que inicia, sostiene y completa la tarea en aula.','Horas contratadas del profesional.','Número de documentos archivados.'],1],
    ['Aplicación','Un apoyo no produce progreso tras el periodo acordado. ¿Qué corresponde?',['Mantenerlo indefinidamente.','Revisar fidelidad de implementación, barreras, intensidad y evidencia; luego ajustar la hipótesis o acción.','Responsabilizar al estudiante.','Cerrar el plan.'],1],
    ['Decisión pedagógica','¿Qué organización favorece más la inclusión?',['Apoyos desconectados del aula y del OA.','Planificación colaborativa, apoyos en contextos pertinentes y responsabilidades compartidas.','Intervención exclusiva del especialista.','Decisiones sin estudiante ni familia.'],1]
  ], collaboration: [
    ['Comprensión conceptual','¿Qué caracteriza un trabajo colaborativo efectivo?',['Repartir tareas sin propósito común.','Construir objetivos compartidos, roles complementarios y decisiones basadas en evidencia.','Derivar todas las decisiones al especialista.','Realizar reuniones frecuentes sin seguimiento.'],1],
    ['Comprensión conceptual','¿Cómo debe comunicarse un resultado de evaluación a la familia?',['Solo con términos técnicos.','De forma comprensible, respetuosa y orientada a fortalezas, necesidades, apoyos y acciones.','Únicamente mediante puntajes.','Sin permitir preguntas.'],1],
    ['Interpretación','Docente y especialista trabajan con el mismo estudiante, pero usan objetivos y apoyos distintos sin comunicarse. ¿Qué problema existe?',['Exceso de inclusión.','Fragmentación que dificulta coherencia y seguimiento.','Demasiada participación familiar.','Falta de diagnóstico médico.'],1],
    ['Interpretación','En una reunión se informa un plan ya decidido y se pide a la familia firmar. ¿Qué falta?',['Más formularios.','Participación auténtica en la comprensión y toma de decisiones.','Una prueba adicional.','Reducir la duración de la reunión.'],1],
    ['Aplicación','¿Qué agenda favorece una reunión de equipo útil?',['Revisar etiquetas y distribuir documentos.','Analizar evidencia, priorizar una necesidad, acordar acciones, responsables, indicadores y fecha de revisión.','Conversar sin registrar acuerdos.','Planificar apoyos fuera del aula únicamente.'],1],
    ['Aplicación','Un estudiante señala que un apoyo lo hace sentirse expuesto. ¿Qué corresponde?',['Ignorarlo porque el apoyo funciona.','Incorporar su perspectiva y rediseñar una alternativa efectiva y menos estigmatizante.','Retirar todo apoyo de inmediato.','Informar solo a la familia.'],1],
    ['Aplicación','¿Qué comunicación protege mejor la confidencialidad?',['Compartir el diagnóstico con todo el personal.','Entregar a cada participante solo la información pertinente para su rol, por canales resguardados.','Comentar el caso en espacios comunes.','Usar grupos abiertos de mensajería.'],1],
    ['Decisión pedagógica','Ante desacuerdo entre familia y escuela, ¿qué acción es más adecuada?',['Imponer la decisión profesional.','Escuchar perspectivas, volver a la evidencia y derechos, explicitar acuerdos y definir revisión conjunta.','Suspender apoyos.','Evitar futuras reuniones.'],1]
  ]};
  const questions = questionSets[quiz.dataset.quiz || 'bio'];
  const letters=['A','B','C','D'];
  quiz.innerHTML=questions.map((x,i)=>`<fieldset class="quiz-question"><legend><span>${i+1} de ${questions.length} · ${x[0]}${x[4] ? ` · ${x[4]}` : ''}</span>${x[1]}</legend>${x[2].map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"><span><strong>${letters[j]}</strong>${o}</span></label>`).join('')}</fieldset>`).join('')+'<p class="quiz-error" role="alert" tabindex="-1" hidden>Responde todas las preguntas antes de finalizar.</p><button class="button green-button quiz-submit">Ver mi resultado</button>';
  quiz.addEventListener('submit',(event)=>{event.preventDefault();const data=new FormData(quiz);if(questions.some((_,i)=>!data.has(`q${i}`))){const e=quiz.querySelector('.quiz-error');e.hidden=false;e.focus();return;}let total=0;const stats={},units={};questions.forEach((x,i)=>{const ok=Number(data.get(`q${i}`))===x[3];total+=ok;stats[x[0]]??={correct:0,total:0};stats[x[0]].total++;stats[x[0]].correct+=ok;if(x[4]){units[x[4]]??={correct:0,total:0};units[x[4]].total++;units[x[4]].correct+=ok;}});const sorted=Object.entries(stats).sort((a,b)=>b[1].correct/b[1].total-a[1].correct/a[1].total);document.querySelector('#result-percent').textContent=`${Math.round(total/questions.length*100)}%`;document.querySelector('#result-score').textContent=`${total} de ${questions.length}`;document.querySelector('#result-strength').textContent=sorted[0][0].toLowerCase();document.querySelector('#result-improve').textContent=sorted.at(-1)[0].toLowerCase();const bars=(source)=>Object.entries(source).map(([n,v])=>{const p=Math.round(v.correct/v.total*100);return `<article><div><strong>${n}</strong><span>${v.correct}/${v.total} · ${p}%</span></div><div class="mini-progress green" role="progressbar" aria-label="${n}: ${p} por ciento"><span style="width:${p}%"></span></div></article>`}).join('');document.querySelector('#skill-breakdown').innerHTML=bars(stats);const unitBreakdown=document.querySelector('#unit-breakdown');if(unitBreakdown)unitBreakdown.innerHTML=bars(units);const result=document.querySelector('#resultado');result.hidden=false;result.scrollIntoView({behavior:'smooth'});result.querySelector('h2').focus({preventScroll:true});});
  document.querySelector('#retry-quiz').addEventListener('click',()=>{quiz.reset();document.querySelector('#resultado').hidden=true;quiz.querySelector('.quiz-error').hidden=true;document.querySelector('#practica').scrollIntoView({behavior:'smooth'});});
});
