document.addEventListener('DOMContentLoaded', () => {
  const demoButtons = document.querySelectorAll('[data-demo-message]');
  if (demoButtons.length) {

  const toast = document.createElement('div');
  toast.className = 'toast';
  toast.setAttribute('role', 'status');
  toast.setAttribute('aria-live', 'polite');
  toast.hidden = true;
  document.body.appendChild(toast);

  let timer;
  demoButtons.forEach((button) => {
    button.addEventListener('click', () => {
      clearTimeout(timer);
      toast.textContent = button.dataset.demoMessage;
      toast.hidden = false;
      timer = setTimeout(() => { toast.hidden = true; }, 3800);
    });
  }); }

  const quickCheck = document.querySelector('[data-single-question]');
  if (quickCheck) quickCheck.addEventListener('submit', (event) => {
    event.preventDefault(); const value = new FormData(quickCheck).get('check');
    const correct = quickCheck.dataset.correct || 'b';
    quickCheck.querySelector('.inline-feedback').textContent = !value ? 'Selecciona una alternativa antes de revisar.' : value === correct ? (quickCheck.dataset.success || '¡Correcto! Aplicaste el criterio central de esta unidad.') : (quickCheck.dataset.retry || 'Aún no. Vuelve a comparar las características de cada enfoque.');
  });

  const quiz = document.querySelector('#ecep-quiz'); if (!quiz) return;
  const questionSets = { bio: [
    ['Comprensión conceptual','¿Qué distingue al modelo biopsicosocial?',['Explica el desempeño solo desde el diagnóstico.','Comprende el funcionamiento como interacción entre factores individuales y contextuales.','Considera que todos requieren los mismos apoyos.','Reemplaza la observación pedagógica por información clínica.'],1],
    ['Comprensión conceptual','¿Cuál afirmación es coherente con este modelo?',['Las características individuales dejan de ser relevantes.','Toda dificultad se origina en el ambiente.','Una característica puede expresarse distinto según las condiciones de participación.','Los apoyos dependen solo del diagnóstico.'],2],
    ['Interpretación','Una estudiante participa más cuando anticipa la rutina con imágenes. ¿Qué permite interpretar?',['La respuesta depende también de los apoyos disponibles.','No necesita nuevos desafíos.','La dificultad desapareció definitivamente.','Las imágenes deben reemplazar toda instrucción oral.'],0],
    ['Interpretación','Un informe dice “no completa tareas porque presenta DEA”. ¿Qué falta?',['Una calificación más baja.','Información sobre contexto, demandas y apoyos usados.','Confirmar que la dificultad es permanente.','Comparar solo con el promedio.'],1],
    ['Aplicación','Valentina responde mejor a instrucciones orales y visuales. ¿Qué acción es coherente?',['Mantener solo instrucciones escritas.','Reducir todos los objetivos.','Combinar formatos y observar qué favorece autonomía y comprensión.','Separarla del trabajo grupal.'],2],
    ['Aplicación','Un estudiante resuelve con material concreto, pero se bloquea ante símbolos. ¿Qué harías?',['Concluir que no comprende matemática.','Planificar una transición entre representaciones y registrar su respuesta.','Eliminar los problemas.','Repetir ejercicios sin cambios.'],1],
    ['Aplicación','Una estudiante aporta por escrito, pero no habla en debates. ¿Qué análisis es más completo?',['No tiene ideas.','Solo es timidez.','Explorar factores personales, dinámica grupal y alternativas de comunicación.','Evaluar solo oralmente.'],2],
    ['Decisión pedagógica','Ante baja participación, ¿qué decisión refleja mejor el modelo?',['Asignar una etiqueta y mantener la planificación.','Cambiar todas las metas sin evidencia.','Ofrecer apoyos, observar la respuesta y ajustar la enseñanza.','Esperar que se adapte sola.'],2]
  ], evolution: [
    ['Comprensión conceptual','¿Qué caracteriza al enfoque homogeneizador?',['Reconoce múltiples formas de aprender.','Espera que el grupo avance de una manera uniforme.','Elimina las barreras del entorno.','Prioriza la participación en el aula común.'],1],
    ['Comprensión conceptual','¿Qué cambio representa el enfoque inclusivo?',['Traslada al estudiante a un espacio separado.','Busca que la persona se adapte sin modificar la escuela.','Transforma culturas, políticas y prácticas para responder a la diversidad.','Clasifica para enseñar según el déficit.'],2],
    ['Interpretación','Una escuela agrupa permanentemente al alumnado según diagnóstico y ofrece un currículo reducido. ¿Qué enfoque predomina?',['Déficit y categorización.','Inclusión.','Diversidad.','Diseño universal.'],0],
    ['Interpretación','Un estudiante asiste al aula común, pero debe realizar exactamente las mismas tareas sin apoyos. ¿Qué tensión se observa?',['Participación plena.','Presencia física sin transformación de las condiciones.','Eliminación de barreras.','Diversificación de la enseñanza.'],1],
    ['Aplicación','Un equipo afirma que Emilia debe “estar preparada” antes de participar con su curso. ¿Qué revisión corresponde?',['Mantenerla fuera hasta que alcance el promedio.','Preguntar qué apoyos y cambios permitirían su participación ahora.','Reducir sus oportunidades de interacción.','Aplicar una prueba para justificar la separación.'],1],
    ['Aplicación','La clase contempla distintas formas de acceder, participar y demostrar lo aprendido. ¿Qué enfoque expresa mejor?',['Homogeneizador.','Déficit.','Normalización entendida como asimilación.','Diversidad e inclusión.'],3],
    ['Aplicación','Un profesor detecta que una actividad excluye a quienes requieren más tiempo. ¿Qué acción refleja evolución hacia la inclusión?',['Atribuir el problema a los estudiantes.','Ofrecer tiempo flexible y revisar la demanda de la tarea.','Retirar a quienes no terminan.','Mantener la actividad para asegurar igualdad.'],1],
    ['Decisión pedagógica','¿Qué decisión es más coherente con una educación inclusiva?',['Diseñar primero para un estudiante promedio y adaptar al final.','Separar apoyos de la planificación del curso.','Planificar desde la diversidad y ajustar apoyos según evidencias de participación.','Usar el diagnóstico como único criterio para decidir.'],2]
  ], inclusion: [
    ['Comprensión conceptual','¿Qué es una barrera para el aprendizaje y la participación?',['Una condición fija del estudiante.','Una dificultad que surge de la interacción con condiciones del contexto.','Un diagnóstico que determina el rendimiento.','Una conducta que debe corregirse antes de participar.'],1],
    ['Comprensión conceptual','¿Qué describe mejor una necesidad de apoyo?',['Una etiqueta permanente.','Una razón para reducir siempre los objetivos.','El apoyo requerido para acceder, aprender o participar en una situación.','Una característica exclusiva de estudiantes con diagnóstico.'],2],
    ['Interpretación','La plataforma de lectura no admite lector de pantalla. ¿Dónde se ubica principalmente la barrera?',['En la capacidad del estudiante.','En el recurso tecnológico y su diseño.','En la familia.','En el objetivo de aprendizaje.'],1],
    ['Interpretación','Una familia migrante no comprende las comunicaciones escolares porque solo se envían con lenguaje técnico. ¿Qué análisis corresponde?',['Falta de interés familiar.','Una barrera comunicacional y cultural que la escuela puede modificar.','Una necesidad de diagnóstico.','Un problema ajeno a la enseñanza.'],1],
    ['Aplicación','Algunos estudiantes requieren más tiempo para organizar una respuesta escrita. ¿Qué estrategia diversificada es pertinente?',['Bajar la expectativa de aprendizaje.','Ofrecer tiempo flexible y apoyos para planificar, manteniendo el objetivo.','Excluir la producción escrita.','Evaluar solamente rapidez.'],1],
    ['Aplicación','En una actividad oral, una estudiante comunica mejor sus ideas mediante imágenes y palabras clave. ¿Qué harías?',['Aceptar distintas formas de expresión alineadas con el objetivo.','Exigir solo exposición oral.','Reemplazar el objetivo por uno más fácil.','Pedir que observe sin participar.'],0],
    ['Aplicación','El curso estudia relatos de distintas comunidades. ¿Qué acción fortalece inclusión y multiculturalidad?',['Presentar una cultura como norma.','Evitar diferencias para prevenir conflictos.','Incorporar voces diversas y revisar estereotipos con participación del grupo.','Asignar a estudiantes migrantes la tarea de representar a toda su cultura.'],2],
    ['Decisión pedagógica','Ante baja participación de varios estudiantes, ¿qué debería hacer primero el equipo?',['Derivarlos individualmente.','Revisar las barreras de la actividad, recoger sus perspectivas y diversificar apoyos.','Mantener la actividad para comparar resultados.','Reducir el currículo del grupo.'],1]
  ], regulations: [
    ['Comprensión conceptual','¿Qué instrumento reconoce el derecho a un sistema de educación inclusivo en todos los niveles?',['Decreto 170.','Convención sobre los Derechos de las Personas con Discapacidad.','Decreto 67.','Reglamento interno.'],1],
    ['Comprensión conceptual','¿Cuál es el propósito central del Decreto 170?',['Regular toda evaluación escolar.','Fijar criterios para identificar estudiantes con NEE beneficiarios de subvención de educación especial.','Prohibir la selección escolar.','Definir adecuaciones curriculares.'],1],
    ['Interpretación','Un equipo necesita decidir cómo diversificar y, si es necesario, adecuar el currículo en educación básica. ¿Qué norma es directamente pertinente?',['Decreto 83 de 2015.','Ley 20.845 exclusivamente.','Decreto 170 exclusivamente.','PNCE 2024–2030 exclusivamente.'],0],
    ['Interpretación','Una escuela usa una única prueba y no permite ajustes coherentes con la enseñanza. ¿Qué norma orienta especialmente la evaluación para favorecer el progreso?',['Ley 20.422.','Decreto 67 de 2018.','Ley 20.845.','Convención, artículo sobre accesibilidad física únicamente.'],1],
    ['Aplicación','Antes de decidir una adecuación curricular individual, ¿qué corresponde según el Decreto 83?',['Aplicarla automáticamente por diagnóstico.','Implementar diversificación y evaluar si resulta insuficiente.','Eliminar objetivos básicos.','Esperar una calificación insuficiente.'],1],
    ['Aplicación','Una escuela niega matrícula por discapacidad. ¿Qué marco resulta vulnerado de manera directa?',['Solo su calendario escolar.','Igualdad de oportunidades, no discriminación e inclusión.','Únicamente las reglas de calificación.','Solo la planificación de aula.'],1],
    ['Aplicación','Ante conflictos reiterados, el equipo propone únicamente sanciones. ¿Qué aporta la PNCE 2024–2030?',['Un enfoque formativo, participativo, de cuidado colectivo e inclusión.','Un procedimiento para diagnosticar DEA.','Criterios de promoción anual.','Una tabla de adecuaciones curriculares.'],0],
    ['Decisión pedagógica','¿Cuál uso de la normativa es profesionalmente más adecuado?',['Memorizar números sin analizar la situación.','Aplicar una norma aislada aunque contradiga derechos.','Identificar el derecho o proceso implicado, articular normas pertinentes y justificar la decisión pedagógica.','Usar siempre el Decreto 170 para cualquier necesidad.'],2]
  ], decree83: [
    ['Comprensión conceptual','¿Qué debe ocurrir antes de considerar una adecuación curricular individual?',['Asignar un diagnóstico.','Implementar estrategias diversificadas y evaluar su efecto.','Reducir los objetivos del estudiante.','Separar al estudiante del curso.'],1],
    ['Comprensión conceptual','¿Cuál alternativa corresponde a una adecuación de acceso?',['Graduar la complejidad de un objetivo.','Eliminar un aprendizaje básico imprescindible.','Modificar el formato de presentación o respuesta sin cambiar el objetivo.','Cambiar el nivel educativo del objetivo.'],2],
    ['Interpretación','Una estudiante demuestra el mismo aprendizaje usando teclado en vez de escritura manual. ¿Qué tipo de decisión es?',['Adecuación de acceso.','Adecuación a un objetivo.','Eliminación de un objetivo.','Promoción automática.'],0],
    ['Interpretación','Tras apoyos diversificados, un estudiante mantiene un desfase significativo y el equipo gradúa la complejidad de un OA. ¿Qué representa?',['Una estrategia general para todo el curso.','Una adecuación curricular a los objetivos de aprendizaje.','Una eximición sin evaluación.','Una adecuación exclusivamente física.'],1],
    ['Aplicación','Un curso presenta dificultades para comprender instrucciones extensas. ¿Cuál es la primera respuesta más coherente?',['Crear de inmediato un plan individual para cada estudiante.','Diversificar las instrucciones con ejemplos, segmentos y apoyos visuales.','Eliminar el objetivo para todo el curso.','Solicitar diagnóstico antes de modificar la clase.'],1],
    ['Aplicación','Un estudiante comprende contenidos, pero no accede a un texto impreso por baja visión. ¿Qué medida mantiene el objetivo?',['Texto ampliado o formato digital accesible.','Eliminar la lectura del currículo.','Sustituir el objetivo por uno de nivel inferior.','Calificar solo la asistencia.'],0],
    ['Aplicación','¿Qué evidencia justifica mejor una adecuación curricular individual?',['La preferencia aislada de un adulto.','El diagnóstico por sí solo.','Evaluación amplia de necesidades y respuesta insuficiente a la diversificación implementada.','Una única calificación baja.'],2],
    ['Decisión pedagógica','¿Qué decisión respeta mejor el Decreto 83?',['Eliminar primero objetivos para evitar frustración.','Usar adecuaciones idénticas para una misma categoría diagnóstica.','Seleccionar el ajuste menos significativo que permita participación y progreso, monitorearlo y revisarlo.','Mantener una adecuación sin evaluar sus resultados.'],2]
  ], integration: [
    ['Comprensión conceptual','¿Qué idea resume mejor el modelo biopsicosocial?',['La dificultad pertenece exclusivamente al estudiante.','El funcionamiento surge de la interacción entre características personales y contexto.','El contexto explica por sí solo todo desempeño.','El diagnóstico determina la respuesta educativa.'],1,'Unidad 1'],
    ['Interpretación','Una estudiante mejora al recibir anticipación visual. ¿Qué interpretación es más completa?',['La respuesta evidencia interacción entre sus características y el apoyo.','La dificultad desapareció.','Solo necesita imágenes.','El objetivo debe reducirse.'],0,'Unidad 1'],
    ['Decisión pedagógica','¿Qué harías ante un desempeño que cambia según el formato de instrucción?',['Mantener un único formato.','Observar condiciones, diversificar apoyos y evaluar la respuesta.','Derivar antes de modificar.','Calificar el déficit.'],1,'Unidad 1'],
    ['Comprensión conceptual','¿Qué distingue inclusión de integración asimilacionista?',['La inclusión exige que el estudiante se adapte.','La inclusión transforma condiciones para asegurar participación y aprendizaje.','La integración siempre elimina barreras.','No existe diferencia pedagógica.'],1,'Unidad 2'],
    ['Interpretación','Un estudiante está en aula común, pero sin apoyos y con exigencia uniforme. ¿Qué refleja?',['Inclusión plena.','Presencia física sin transformación suficiente.','Diversificación universal.','Adecuación de acceso.'],1,'Unidad 2'],
    ['Aplicación','¿Qué acción expresa evolución hacia un enfoque inclusivo?',['Agrupar permanentemente por diagnóstico.','Diseñar desde la diversidad y revisar barreras.','Esperar preparación previa para participar.','Reducir expectativas por categoría.'],1,'Unidad 2'],
    ['Comprensión conceptual','¿Qué es una barrera para el aprendizaje y la participación?',['Una condición fija individual.','Una dificultad producida en la interacción con condiciones del contexto.','Un sinónimo de diagnóstico.','Una falta de esfuerzo.'],1,'Unidad 3'],
    ['Interpretación','Una comunicación técnica excluye a familias que no dominan ese registro. ¿Qué barrera predomina?',['Comunicacional y cultural.','Motora.','Diagnóstica.','Curricular individual.'],0,'Unidad 3'],
    ['Aplicación','¿Qué respuesta conserva el objetivo y amplía la participación?',['Una única forma de demostrar aprendizaje.','Alternativas de expresión alineadas con el propósito.','Eliminar el contenido complejo.','Separar a quienes requieren apoyo.'],1,'Unidad 3'],
    ['Comprensión conceptual','¿Qué norma regula especialmente evaluación, calificación y promoción?',['Decreto 170.','Decreto 67 de 2018.','Ley 20.845.','PNCE 2024–2030.'],1,'Unidad 4'],
    ['Interpretación','¿Qué norma consulta directamente un equipo para identificar beneficiarios de subvención de educación especial?',['Decreto 170.','Decreto 83 de 2015.','Decreto 67.','Ley 20.845.'],0,'Unidad 4'],
    ['Decisión pedagógica','¿Cómo debe usarse la normativa ante un caso complejo?',['Elegir un número de memoria.','Articular derechos, norma específica y evidencia pedagógica.','Aplicar siempre una sola norma.','Priorizar procedimientos sobre derechos.'],1,'Unidad 4'],
    ['Comprensión conceptual','¿Cuál es la secuencia correcta del Decreto 83?',['Adecuar, diagnosticar y luego diversificar.','Diversificar, evaluar la respuesta y adecuar si es necesario.','Eliminar objetivos y observar.','Calificar y luego apoyar.'],1,'Unidad 5'],
    ['Interpretación','Usar teclado manteniendo el objetivo de producción escrita corresponde a:',['Adecuación de acceso.','Eliminación del objetivo.','Promoción especial.','Adecuación por temporalización.'],0,'Unidad 5'],
    ['Aplicación','¿Qué sustenta una adecuación a los OA?',['Solo el diagnóstico.','Evaluación amplia, evidencia de apoyos previos insuficientes y monitoreo.','Una preferencia del docente.','Una prueba aislada.'],1,'Unidad 5']
  ], assessment: [
    ['Comprensión conceptual','¿Qué caracteriza una evaluación integral?',['Utiliza una sola prueba estandarizada.','Articula diversas fuentes, profesionales y contextos para orientar apoyos.','Busca únicamente confirmar un diagnóstico.','Se realiza sin participación de la familia.'],1],
    ['Comprensión conceptual','¿Cuál es su propósito educativo central?',['Clasificar al estudiante.','Justificar una calificación.','Identificar fortalezas, necesidades de apoyo y una respuesta educativa pertinente.','Comparar exclusivamente con el promedio.'],2],
    ['Interpretación','Un informe contiene puntajes, pero no describe desempeño en aula, contexto ni apoyos probados. ¿Qué falta?',['Más etiquetas clínicas.','Una comprensión contextual y funcional del aprendizaje.','Eliminar la entrevista familiar.','Una calificación final.'],1],
    ['Interpretación','La familia informa que el estudiante resuelve tareas cotidianas que no logra mostrar en una prueba. ¿Cómo usar ese antecedente?',['Descartarlo por no ser escolar.','Integrarlo como evidencia relevante y contrastarlo con otras fuentes.','Reemplazar toda evaluación profesional.','Usarlo solo si confirma el déficit.'],1],
    ['Aplicación','¿Qué conjunto entrega evidencia más completa?',['Una prueba aislada.','Observación, producciones, entrevistas, evaluación curricular y antecedentes pertinentes.','Solo promedio de notas.','Solo diagnóstico médico.'],1],
    ['Aplicación','Un estudiante progresa al recibir apoyos visuales. ¿Qué debe registrar el equipo?',['Solo que respondió bien.','Condiciones, tipo de apoyo, nivel de autonomía y cambios en participación y aprendizaje.','Únicamente la fecha.','La categoría diagnóstica.'],1],
    ['Aplicación','¿Cómo deben comunicarse los resultados a la familia?',['Con tecnicismos y puntajes exclusivamente.','De manera comprensible, incluyendo fortalezas, necesidades, apoyos y acciones del establecimiento.','Solo mediante el diagnóstico.','Sin mencionar el contexto escolar.'],1],
    ['Decisión pedagógica','Tras evaluar, ¿qué decisión es más pertinente?',['Aplicar el mismo apoyo a estudiantes con igual diagnóstico.','Planificar apoyos vinculados con la evidencia, responsables y seguimiento.','Archivar el informe sin modificar la enseñanza.','Esperar la reevaluación para actuar.'],1]
  ], psychoeducational: [
    ['Comprensión conceptual','¿Qué distingue la evaluación curricular de una medición aislada?',['Describe únicamente un puntaje.','Analiza el desempeño respecto del currículo, las tareas y condiciones de enseñanza.','Confirma por sí sola un diagnóstico.','Excluye la observación del aula.'],1],
    ['Comprensión conceptual','¿Qué significa triangular evidencia?',['Repetir tres veces la misma prueba.','Contrastar información de distintas fuentes, métodos y momentos.','Promediar todas las calificaciones.','Elegir el resultado más bajo.'],1],
    ['Interpretación','Un estudiante falla en una prueba descontextualizada, pero aplica la habilidad en tareas de aula con apoyos. ¿Qué corresponde concluir?',['No posee la habilidad.','La evidencia es divergente y deben analizarse las demandas y apoyos antes de concluir.','La prueba debe ignorarse siempre.','Debe reducirse el objetivo.'],1],
    ['Interpretación','Dos tareas evalúan comprensión, pero una exige mucha escritura. El desempeño cambia. ¿Qué variable debe examinarse?',['La demanda de respuesta escrita como posible interferencia.','Solo la motivación.','El diagnóstico médico.','La asistencia anual.'],0],
    ['Aplicación','¿Qué procedimiento es más pertinente para conocer estrategias lectoras?',['Solo registrar velocidad.','Combinar lectura, preguntas, verbalización de estrategias y análisis de errores.','Aplicar una encuesta familiar únicamente.','Revisar la nota final.'],1],
    ['Aplicación','Antes de aplicar un instrumento, el profesional debe verificar principalmente:',['Que sea el más corto.','Su propósito, pertinencia, condiciones de aplicación y límites interpretativos.','Que produzca un diagnóstico.','Que todos obtengan resultados comparables sin ajustes.'],1],
    ['Aplicación','¿Qué redacción interpreta evidencia con mayor rigor?',['No puede aprender fracciones.','En tareas simbólicas sin apoyo comete errores de equivalencia; con representación visual identifica relaciones y explica su estrategia.','Tiene bajo rendimiento general.','Su diagnóstico explica los errores.'],1],
    ['Decisión pedagógica','La evidencia muestra una barrera de formato, no del objetivo. ¿Qué decisión corresponde?',['Modificar inmediatamente el OA.','Ajustar el acceso o la respuesta y volver a recoger evidencia del mismo aprendizaje.','Suspender la evaluación.','Mantener el formato para comparar.'],1]
  ], deaIdentification: [
    ['Comprensión conceptual','¿Qué rasgo es necesario considerar al evaluar una posible DEA?',['Una dificultad aislada en cualquier asignatura.','Dificultad significativa y persistente en lectura, lectura-escritura o matemática pese a medidas pedagógicas pertinentes.','Una calificación insuficiente.','La preferencia por apoyos visuales.'],1],
    ['Comprensión conceptual','¿Por qué es necesario el diagnóstico diferencial?',['Para encontrar más etiquetas.','Para examinar si el desempeño se explica mejor por factores sensoriales, intelectuales, emocionales, ambientales o de enseñanza.','Para reemplazar la evaluación curricular.','Para excluir a la familia.'],1],
    ['Interpretación','Un curso completo presenta bajo desempeño tras meses sin enseñanza sistemática de lectura. ¿Qué interpretación es prioritaria?',['Todos presentan DEA.','Debe revisarse la oportunidad y calidad de enseñanza antes de atribuir dificultades específicas individuales.','Se confirma una dificultad crónica.','Basta una prueba estandarizada.'],1],
    ['Interpretación','Una estudiante mejora rápidamente con enseñanza explícita y práctica guiada. ¿Qué indica esta respuesta?',['Confirma necesariamente DEA.','La dificultad era inmodificable.','La respuesta al apoyo es evidencia relevante que obliga a revisar hipótesis antes de diagnosticar.','Debe suspenderse el apoyo.'],2],
    ['Aplicación','¿Qué antecedente demuestra mejor persistencia?',['Una prueba baja.','Registros longitudinales de progreso bajo medidas pedagógicas pertinentes y monitoreadas.','La opinión aislada de un adulto.','Una ausencia escolar.'],1],
    ['Aplicación','Antes de derivar, el equipo detecta dificultades lectoras. ¿Qué acción corresponde?',['Esperar sin intervenir.','Implementar enseñanza diversificada, apoyo focalizado y monitoreo continuo, documentando la respuesta.','Asignar diagnóstico provisorio.','Reducir los objetivos.'],1],
    ['Aplicación','En la evaluación aparecen dificultades y antecedentes de visión no corregida. ¿Qué procede?',['Ignorar el antecedente.','Concluir DEA por los puntajes.','Asegurar evaluación de salud y analizar cuánto explica el acceso visual antes de concluir.','Aplicar más tareas impresas.'],2],
    ['Decisión pedagógica','¿Cuál decisión es más rigurosa ante evidencia todavía ambigua?',['Confirmar DEA para acceder rápido a recursos.','Mantener apoyos, ampliar evidencia interdisciplinaria y contrastar explicaciones alternativas.','Retirar apoyos hasta tener diagnóstico.','Usar solo el resultado más bajo.'],1]
  ], supportPlanning: [
    ['Comprensión conceptual','¿Qué función cumple un Plan de Apoyo Individual (PAI)?',['Registrar solo el diagnóstico.','Organizar apoyos, responsables y ajustes derivados de la evaluación integral.','Reemplazar la planificación del curso.','Modificar siempre los OA.'],1],
    ['Comprensión conceptual','¿Cuándo forma parte del PAI un PACI?',['Para todo estudiante con apoyo.','Cuando se requieren adecuaciones significativas a los objetivos de aprendizaje.','Ante cualquier ajuste de acceso.','Solo por solicitud familiar.'],1],
    ['Interpretación','Un plan dice “mejorar lectura” sin acción, responsable ni indicador. ¿Cuál es su principal debilidad?',['Tiene demasiada información.','No permite implementar ni evaluar el apoyo.','Debe incluir un diagnóstico nuevo.','Necesita reducir objetivos.'],1],
    ['Interpretación','El apoyo mejora precisión, pero el estudiante sigue dependiendo totalmente del adulto. ¿Qué debe analizarse?',['Solo mantenerlo.','Eficacia y también autonomía, intensidad y posibilidad de retirar ayudas gradualmente.','Cambiar el diagnóstico.','Aumentar todas las ayudas.'],1],
    ['Aplicación','¿Cuál objetivo de apoyo es más observable?',['Fortalecer comprensión.','En ocho semanas, identificará ideas centrales usando organizador visual con ayuda gradualmente decreciente en 4 de 5 textos.','Mejorar mucho.','Trabajar lectura semanalmente.'],1],
    ['Aplicación','¿Qué indicador informa mejor sobre participación?',['Cantidad de sesiones realizadas.','Frecuencia y autonomía con que inicia, sostiene y completa la tarea en aula.','Horas contratadas del profesional.','Número de documentos archivados.'],1],
    ['Aplicación','Un apoyo no produce progreso tras el periodo acordado. ¿Qué corresponde?',['Mantenerlo indefinidamente.','Revisar fidelidad de implementación, barreras, intensidad y evidencia; luego ajustar la hipótesis o acción.','Responsabilizar al estudiante.','Cerrar el plan.'],1],
    ['Decisión pedagógica','¿Qué organización favorece más la inclusión?',['Apoyos desconectados del aula y del OA.','Planificación colaborativa, apoyos en contextos pertinentes y responsabilidades compartidas.','Intervención exclusiva del especialista.','Decisiones sin estudiante ni familia.'],1]
  ], collaboration: [
    ['Comprensión conceptual','¿Qué caracteriza un trabajo colaborativo efectivo?',['Repartir tareas sin propósito común.','Construir objetivos compartidos, roles complementarios y decisiones basadas en evidencia.','Derivar todas las decisiones al especialista.','Realizar reuniones frecuentes sin seguimiento.'],1],
    ['Comprensión conceptual','¿Cómo debe comunicarse un resultado de evaluación a la familia?',['Solo con términos técnicos.','De forma comprensible, respetuosa y orientada a fortalezas, necesidades, apoyos y acciones.','Únicamente mediante puntajes.','Sin permitir preguntas.'],1],
    ['Interpretación','Docente y especialista trabajan con el mismo estudiante, pero usan objetivos y apoyos distintos sin comunicarse. ¿Qué problema existe?',['Exceso de inclusión.','Fragmentación que dificulta coherencia y seguimiento.','Demasiada participación familiar.','Falta de diagnóstico médico.'],1],
    ['Interpretación','En una reunión se informa un plan ya decidido y se pide a la familia firmar. ¿Qué falta?',['Más formularios.','Participación auténtica en la comprensión y toma de decisiones.','Una prueba adicional.','Reducir la duración de la reunión.'],1],
    ['Aplicación','¿Qué agenda favorece una reunión de equipo útil?',['Revisar etiquetas y distribuir documentos.','Analizar evidencia, priorizar una necesidad, acordar acciones, responsables, indicadores y fecha de revisión.','Conversar sin registrar acuerdos.','Planificar apoyos fuera del aula únicamente.'],1],
    ['Aplicación','Un estudiante señala que un apoyo lo hace sentirse expuesto. ¿Qué corresponde?',['Ignorarlo porque el apoyo funciona.','Incorporar su perspectiva y rediseñar una alternativa efectiva y menos estigmatizante.','Retirar todo apoyo de inmediato.','Informar solo a la familia.'],1],
    ['Aplicación','¿Qué comunicación protege mejor la confidencialidad?',['Compartir el diagnóstico con todo el personal.','Entregar a cada participante solo la información pertinente para su rol, por canales resguardados.','Comentar el caso en espacios comunes.','Usar grupos abiertos de mensajería.'],1],
    ['Decisión pedagógica','Ante desacuerdo entre familia y escuela, ¿qué acción es más adecuada?',['Imponer la decisión profesional.','Escuchar perspectivas, volver a la evidencia y derechos, explicitar acuerdos y definir revisión conjunta.','Suspender apoyos.','Evitar futuras reuniones.'],1]
  ], readingProcesses: [
    ['Comprensión conceptual','¿Qué describe mejor la decodificación?',['Comprender las intenciones del autor.','Relacionar representaciones escritas y sonidos para reconocer palabras.','Leer siempre con máxima velocidad.','Recordar todos los detalles.'],1],
    ['Comprensión conceptual','¿Qué caracteriza la fluidez lectora?',['Solo la cantidad de palabras por minuto.','Precisión, ritmo y expresión que favorecen la comprensión.','Comprensión oral sin lectura.','Conocimiento previo del tema.'],1],
    ['Interpretación','Una estudiante comprende bien el texto escuchado, pero al leerlo sola se detiene y pierde el sentido. ¿Qué hipótesis merece examinarse primero?',['Carece de comprensión oral.','La decodificación o fluidez consume recursos necesarios para comprender.','No posee conocimientos generales.','El texto debe eliminarse.'],1],
    ['Interpretación','Un estudiante lee con precisión y ritmo, responde preguntas literales, pero falla en inferencias. ¿Qué proceso requiere mayor análisis?',['Solo la velocidad.','Comprensión, vocabulario y uso de pistas para inferir.','Trazado de letras.','Reconocimiento visual de palabras.'],1],
    ['Aplicación','¿Qué procedimiento permite distinguir mejor entre dificultad de decodificación y comprensión?',['Aplicar solo lectura en voz alta.','Comparar comprensión del mismo nivel de contenido al leer y al escuchar, junto con precisión y fluidez.','Preguntar si le gusta leer.','Contar únicamente errores ortográficos.'],1],
    ['Aplicación','Una lectora silabea palabras nuevas. ¿Qué apoyo es más coherente?',['Pedirle leer más rápido.','Enseñar correspondencias grafema-fonema, segmentación y combinación con práctica guiada acumulativa.','Entregar solo preguntas literales.','Evitar toda lectura oral.'],1],
    ['Aplicación','Un lector preciso no detecta que una oración contradice el párrafo anterior. ¿Qué conviene enseñar?',['Aumentar palabras por minuto.','Monitorear la comprensión, releer y explicar cómo las ideas se conectan.','Copiar el texto completo.','Memorizar palabras aisladas.'],1],
    ['Decisión pedagógica','Ante errores lectores heterogéneos, ¿qué decisión es más rigurosa?',['Aplicar el mismo entrenamiento de velocidad a todos.','Analizar el patrón por proceso, probar apoyos focalizados y monitorear la respuesta.','Concluir DEA con una observación.','Reducir permanentemente el nivel de los textos.'],1]
  ], decodingFluency: [
    ['Comprensión conceptual','¿Qué componente no puede faltar al analizar fluidez?',['Solo cantidad de palabras por minuto.','Precisión, ritmo y prosodia vinculados con la comprensión.','Caligrafía y ortografía.','Preferencia por leer en silencio.'],1],
    ['Comprensión conceptual','¿Qué indica automatización en lectura?',['Reconocer palabras con menor esfuerzo atencional y conservar recursos para comprender.','Leer cualquier texto a máxima velocidad.','Memorizar un texto después de oírlo.','Evitar palabras desconocidas.'],0],
    ['Interpretación','Un estudiante sustituye palabras por otras que comienzan igual y falla especialmente en pseudopalabras. ¿Qué patrón debe examinarse?',['Inferencias narrativas.','Decodificación y combinación fonológica.','Prosodia exclusivamente.','Motricidad de escritura.'],1],
    ['Interpretación','Una estudiante lee con precisión, pero fragmenta cada oración e ignora puntos y comas. ¿Qué aspecto está más comprometido?',['Reconocimiento de letras.','Prosodia y agrupación en frases.','Comprensión oral.','Ortografía reglada.'],1],
    ['Aplicación','¿Qué apoyo es más pertinente ante dificultades persistentes para combinar sonidos?',['Lecturas cronometradas sin enseñanza.','Modelado explícito, combinación guiada y práctica acumulativa con retroalimentación.','Solo textos más breves.','Memorización de definiciones.'],1],
    ['Aplicación','¿Cómo practicar fluidez sin convertirla en una carrera?',['Premiar únicamente al más rápido.','Usar lectura modelada y repetida con propósito, observando precisión, fraseo y comprensión.','Eliminar toda repetición.','Cronometrar textos cada día sin retroalimentación.'],1],
    ['Aplicación','Tras cuatro semanas aumenta la velocidad, pero también los errores y disminuye la comprensión. ¿Qué corresponde?',['Mantener el entrenamiento porque aumentó la velocidad.','Reajustar el apoyo priorizando precisión y sentido, y analizar cualitativamente los errores.','Elevar la dificultad del texto.','Concluir que la intervención fue exitosa.'],1],
    ['Decisión pedagógica','Dos estudiantes leen lentamente, pero uno decodifica con errores y otro lee preciso con pausas inadecuadas. ¿Qué decisión es más pertinente?',['Aplicar el mismo ejercicio cronometrado.','Diseñar apoyos diferenciados según el patrón y monitorear la respuesta de cada uno.','Reducir los objetivos a ambos.','Evaluar únicamente comprensión oral.'],1]
  ], readingComprehension: [
    ['Comprensión conceptual','¿Qué caracteriza una inferencia lectora?',['Repetir una oración literalmente.','Relacionar pistas del texto y conocimientos pertinentes para construir información implícita.','Pronunciar todas las palabras.','Leer a mayor velocidad.'],1],
    ['Comprensión conceptual','¿Qué significa monitorear la comprensión?',['Memorizar cada detalle.','Comprobar si lo leído tiene sentido y reparar la comprensión cuando es necesario.','Responder solo preguntas literales.','Subrayar todo el texto.'],1],
    ['Interpretación','Un lector preciso desconoce varias palabras centrales y mejora al enseñárselas. ¿Qué indica el patrón?',['La velocidad era la única dificultad.','El vocabulario limitaba la construcción del significado.','Debe reducirse el objetivo lector.','Presenta necesariamente una DEA.'],1],
    ['Interpretación','Una estudiante sostiene una interpretación aunque una oración posterior la contradice. ¿Qué proceso requiere apoyo?',['Decodificación de pseudopalabras.','Monitoreo y ajuste de la comprensión.','Caligrafía.','Conciencia silábica.'],1],
    ['Aplicación','¿Qué práctica favorece el aprendizaje de vocabulario para comprender?',['Copiar definiciones aisladas una vez.','Explicar palabras en contexto, conectarlas con ejemplos y reutilizarlas al interpretar el texto.','Omitir toda palabra difícil.','Evaluar solo pronunciación.'],1],
    ['Aplicación','Para enseñar inferencias sobre la motivación de un personaje, ¿qué corresponde?',['Pedir que adivinen sin justificar.','Modelar cómo combinar pistas textuales y conocimientos, y exigir evidencia para la respuesta.','Aumentar la velocidad de lectura.','Entregar la interpretación final para memorizar.'],1],
    ['Aplicación','Un estudiante se da cuenta de que perdió el sentido. ¿Qué estrategia debe aprender a usar?',['Continuar sin detenerse.','Releer el segmento, identificar el quiebre y ajustar su interpretación.','Copiar el párrafo.','Cambiar inmediatamente de texto.'],1],
    ['Decisión pedagógica','Dos lectores precisos fallan: uno desconoce vocabulario y otro no genera inferencias. ¿Qué decisión es más rigurosa?',['Aplicar a ambos más lectura cronometrada.','Diferenciar apoyos según el proceso y comprobar la respuesta con nuevas evidencias.','Reducir las preguntas a literales.','Concluir que ambos tienen la misma dificultad.'],1]
  ], writingProduction: [
    ['Comprensión conceptual','¿Qué diferencia la transcripción de la composición?',['La transcripción convierte lenguaje en forma escrita; la composición genera, organiza y comunica ideas.','La transcripción solo corresponde a caligrafía.','La composición consiste únicamente en corregir tildes.','No existe diferencia entre ambas.'],0],
    ['Comprensión conceptual','¿Qué implica revisar un texto?',['Copiarlo nuevamente sin cambios.','Evaluar y mejorar contenido, organización, claridad y convenciones según el propósito.','Buscar únicamente faltas ortográficas.','Cambiar todas las palabras.'],1],
    ['Interpretación','Una estudiante relata oralmente ideas complejas, pero escribe muy poco y mejora al dictar. ¿Qué debe examinarse?',['Solo generación de ideas.','La interferencia de la transcripción en la composición.','Únicamente comprensión lectora.','Falta de propósito comunicativo.'],1],
    ['Interpretación','Un estudiante escribe extensamente y con ortografía funcional, pero sus ideas aparecen desordenadas. ¿Qué proceso requiere mayor apoyo?',['Correspondencia grafema-fonema.','Planificación y organización textual.','Trazado de letras.','Velocidad lectora.'],1],
    ['Aplicación','¿Qué apoyo favorece la planificación de un texto argumentativo?',['Corregir cada palabra mientras escribe.','Definir propósito y destinatario, generar razones y organizarlas antes de redactar.','Copiar un texto modelo completo.','Reducir la cantidad de ideas posibles.'],1],
    ['Aplicación','¿Cómo enseñar una revisión sustantiva?',['Pedir que busque solo tildes.','Modelar cómo releer según propósito, detectar un problema de contenido u organización y realizar un cambio.','Entregar la versión corregida.','Evaluar únicamente limpieza.'],1],
    ['Aplicación','Un estudiante pierde ideas porque se detiene ante cada duda ortográfica. ¿Qué respuesta es más pertinente?',['Exigir ortografía perfecta en el primer borrador.','Separar momentos de composición y corrección, junto con enseñanza ortográfica focalizada.','Eliminar toda revisión.','Pedir textos más cortos permanentemente.'],1],
    ['Decisión pedagógica','Ante una producción breve, ¿qué decisión permite intervenir con mayor rigor?',['Aplicar ejercicios de caligrafía a todos.','Comparar modalidades, analizar el proceso y probar apoyos específicos antes de concluir.','Asignar una calificación y esperar.','Reducir el objetivo de escritura.'],1]
  ], literacyIntervention: [
    ['Comprensión conceptual','¿Qué convierte una actividad en una intervención monitoreable?',['Que sea entretenida.','Su vínculo con línea base, objetivo observable, procedimiento, intensidad e indicador.','Que ocurra fuera del aula.','Que utilice muchas fichas.'],1],
    ['Comprensión conceptual','¿Qué es la fidelidad de implementación?',['El grado en que el apoyo se realiza con la dosis y el procedimiento planificados.','La confianza del estudiante en el docente.','La cantidad de evaluaciones aplicadas.','El diagnóstico inicial.'],0],
    ['Interpretación','No hay progreso, pero solo se realizó un tercio de las sesiones y cambió el método. ¿Qué corresponde concluir?',['El estudiante no responde.','La baja fidelidad impide juzgar todavía la eficacia del plan.','Debe confirmarse DEA.','El objetivo era demasiado alto necesariamente.'],1],
    ['Interpretación','Un estudiante usa una estrategia con ayuda en apoyo individual, pero no en aula. ¿Qué falta analizar?',['Solo precisión.','Generalización, autonomía y condiciones para usarla.','El número de palabras por minuto.','La ortografía natural.'],1],
    ['Aplicación','¿Cuál indicador informa mejor el progreso en decodificación?',['Número de sesiones asistidas.','Precisión y tipo de errores en listas equivalentes recogidas periódicamente.','Cantidad de fichas completadas.','Opinión general al final del semestre.'],1],
    ['Aplicación','Una intervención tiene alta fidelidad y progreso mínimo. ¿Qué acción es pertinente?',['Repetirla sin límite.','Revisar la hipótesis, ajustar método o intensidad y ampliar evidencia si corresponde.','Responsabilizar al estudiante.','Suspender todo apoyo.'],1],
    ['Aplicación','El desempeño mejora, pero depende de indicaciones constantes. ¿Qué ajuste favorece autonomía?',['Aumentar las indicaciones para siempre.','Planificar retiro gradual de ayudas y práctica en contextos variados.','Reducir el objetivo.','Evaluar solo en la sesión de apoyo.'],1],
    ['Decisión pedagógica','¿Qué secuencia refleja mejor una toma de decisiones rigurosa?',['Diagnóstico, actividad y calificación.','Línea base, hipótesis, intervención explícita, monitoreo de fidelidad y progreso, ajuste.','Prueba única y derivación.','Apoyo genérico y espera.'],1]
  ], literacyIntegration: [
    ['Comprensión conceptual','¿Qué relación describe mejor la lectura competente?',['La velocidad explica toda comprensión.','Decodificación y lenguaje se coordinan para construir significado.','La comprensión reemplaza el reconocimiento de palabras.','La lectura oral es el único indicador.'],1,'Unidad 1'],
    ['Interpretación','Comprende al escuchar, pero pierde el sentido al leer con muchas pausas. ¿Qué hipótesis se examina primero?',['Comprensión oral insuficiente.','Decodificación o fluidez como cuello de botella.','Falta de ideas.','Ortografía reglada.'],1,'Unidad 1'],
    ['Aplicación','¿Qué evaluación distingue mejor procesos lectores?',['Solo palabras por minuto.','Comparar precisión, fluidez, comprensión oral y comprensión al leer.','Una nota global.','Preferencia de textos.'],1,'Unidad 1'],
    ['Comprensión conceptual','La fluidez integra principalmente:',['Precisión, ritmo y prosodia al servicio del significado.','Velocidad máxima y memoria.','Ortografía y caligrafía.','Solo reconocimiento visual.'],0,'Unidad 2'],
    ['Interpretación','Lee preciso, pero palabra por palabra e ignorando puntuación. ¿Qué requiere apoyo?',['Correspondencia grafema-fonema.','Prosodia y agrupación en frases.','Vocabulario oral.','Planificación escrita.'],1,'Unidad 2'],
    ['Aplicación','Ante fallas en pseudopalabras, ¿qué apoyo es más coherente?',['Cronometrar sin enseñar.','Enseñanza explícita de correspondencias y combinación con práctica acumulativa.','Solo preguntas literales.','Memorizar el texto.'],1,'Unidad 2'],
    ['Comprensión conceptual','Monitorear la comprensión significa:',['Recordar cada detalle.','Comprobar el sentido y reparar cuando se pierde.','Pronunciar más rápido.','Subrayar todo.'],1,'Unidad 3'],
    ['Interpretación','Lee fluido y recupera datos, pero no explica motivaciones. ¿Qué se analiza?',['Solo velocidad.','Inferencias, vocabulario y uso de pistas.','Caligrafía.','Reconocimiento de letras.'],1,'Unidad 3'],
    ['Aplicación','¿Cómo enseñar una inferencia?',['Pedir una adivinanza.','Modelar la relación entre pistas y conocimientos, y justificar con evidencia.','Entregar la respuesta.','Repetir el texto sin propósito.'],1,'Unidad 3'],
    ['Comprensión conceptual','¿Qué pertenece a la composición escrita?',['Solo trazado de letras.','Planificar, textualizar y revisar según un propósito.','Decodificar pseudopalabras.','Leer con prosodia.'],1,'Unidad 4'],
    ['Interpretación','Relata ideas complejas, pero al escribir produce poco y mejora al dictar. ¿Qué sugiere?',['No tiene ideas.','La transcripción interfiere con la composición.','Falta comprensión oral.','Debe reducirse el objetivo.'],1,'Unidad 4'],
    ['Aplicación','¿Qué revisión debe priorizarse antes de las tildes?',['Contenido, propósito y organización global.','Velocidad de copia.','Cantidad de borradores.','Limpieza de la hoja.'],0,'Unidad 4'],
    ['Comprensión conceptual','¿Qué permite juzgar una intervención?',['Sesiones realizadas solamente.','Línea base, indicador de progreso y fidelidad de implementación.','Diagnóstico por sí solo.','Cantidad de fichas.'],1,'Unidad 5'],
    ['Interpretación','No hay progreso y solo se implementó un tercio del plan. ¿Qué corresponde?',['Declarar falta de respuesta.','Corregir la fidelidad antes de juzgar eficacia.','Suspender apoyos.','Cambiar diagnóstico.'],1,'Unidad 5'],
    ['Decisión pedagógica','¿Qué secuencia integra mejor el módulo?',['Manifestación, etiqueta y actividad.','Patrón, hipótesis, objetivo, enseñanza explícita, monitoreo y ajuste.','Prueba aislada y derivación.','Velocidad, calificación y repetición.'],1,'Unidad 5']
  ], mathProcesses: [
    ['Comprensión conceptual','¿Qué describe mejor el sentido numérico?',['Memorizar algoritmos.','Comprender cantidades, magnitudes, orden, composición y relaciones numéricas.','Copiar símbolos con precisión.','Resolver solo problemas verbales.'],1],
    ['Comprensión conceptual','¿Qué función cumplen las representaciones?',['Decorar la actividad.','Hacer visibles relaciones y conectar situaciones con lenguaje matemático.','Reemplazar permanentemente los símbolos.','Reducir el objetivo.'],1],
    ['Interpretación','Resuelve una resta presentada como operación, pero suma en el problema “se retiraron 8”. ¿Qué proceso debe analizarse?',['Cálculo de la resta exclusivamente.','Representación y modelación de la relación descrita.','Escritura de números.','Memoria de hechos multiplicativos.'],1],
    ['Interpretación','Forma 52 con bloques, pero dice que 52 es menor que 48 porque 2 es menor que 8. ¿Qué vínculo falta consolidar?',['Conteo oral.','Valor posicional entre cantidad, lenguaje y símbolo.','Geometría.','Velocidad de cálculo.'],1],
    ['Aplicación','¿Cómo favorecer el tránsito entre representaciones?',['Usar material sin explicarlo.','Pedir construir, dibujar, simbolizar y explicar cómo cada forma representa la misma relación.','Pasar directamente al algoritmo.','Mantener siempre una sola modalidad.'],1],
    ['Aplicación','Un estudiante obtiene 91 para 48 + 32. ¿Qué acción aporta mejor evidencia?',['Marcar incorrecto.','Pedir estimar, representar decenas y unidades y explicar cada paso.','Entregar más ejercicios iguales.','Cambiar de contenido.'],1],
    ['Aplicación','Una estudiante calcula correctamente, pero no comprueba si el resultado es razonable. ¿Qué enseñar?',['Solo rapidez.','Estimación y comparación del resultado con la situación inicial.','Caligrafía numérica.','Memorización de signos.'],1],
    ['Decisión pedagógica','Ante un error matemático persistente, ¿qué decisión es más rigurosa?',['Asignar inmediatamente una etiqueta.','Comparar tareas, representaciones y apoyos, analizar el procedimiento y monitorear la respuesta.','Repetir el algoritmo sin cambios.','Reducir todas las metas.'],1]
  ], numberSense: [
    ['Comprensión conceptual','¿Qué evidencia mejor sentido numérico?',['Recitar números sin error.','Representar, comparar, descomponer y explicar relaciones entre cantidades.','Copiar numerales.','Resolver siempre con un algoritmo.'],1],
    ['Comprensión conceptual','¿Qué expresa el valor posicional?',['La forma del dígito.','El valor que adquiere un dígito según su posición en agrupaciones de base diez.','El orden de escritura solamente.','La cantidad de operaciones.'],1],
    ['Interpretación','Cuenta una colección correctamente, pero al moverla cree que cambió la cantidad. ¿Qué concepto requiere análisis?',['Conservación de cantidad.','Ortografía numérica.','Multiplicación.','Lectura de gráficos.'],0],
    ['Interpretación','Forma 406 con material, pero escribe 46. ¿Qué vínculo falta consolidar?',['Conteo uno a uno.','Función posicional del cero entre agrupación y notación.','Estimación de resultados.','Geometría espacial.'],1],
    ['Aplicación','¿Cómo enseñar comparación de 209 y 89 con comprensión?',['Memorizar una regla aislada.','Representar y comparar desde la posición de mayor valor, justificando la magnitud.','Contar de uno en uno hasta 209.','Copiar el signo mayor que.'],1],
    ['Aplicación','Un estudiante descompone 53 solo como 50 + 3. ¿Qué actividad amplía flexibilidad?',['Repetir esa descomposición.','Buscar y justificar otras equivalencias, como 40 + 13 o 25 + 28.','Memorizar 53.','Pasar a números menores.'],1],
    ['Aplicación','¿Qué favorece una estimación significativa?',['Adivinar antes de mirar.','Usar referentes, comparar magnitudes y explicar un rango razonable.','Contar siempre exactamente.','Aceptar cualquier aproximación.'],1],
    ['Decisión pedagógica','Ante errores posicionales persistentes, ¿qué decisión es más rigurosa?',['Practicar algoritmos sin representación.','Comparar cantidad, material, tabla posicional, lenguaje y símbolo, y monitorear la transferencia.','Reducir el ámbito numérico permanentemente.','Concluir DEA por un error.'],1]
  ], calculationOperations: [
    ['Comprensión conceptual','¿Qué diferencia una estrategia de un algoritmo?',['La estrategia es una elección flexible basada en relaciones; el algoritmo es un procedimiento convencional.','La estrategia siempre es mental y el algoritmo siempre incorrecto.','No existe diferencia.','El algoritmo no usa valor posicional.'],0],
    ['Comprensión conceptual','¿Qué favorece la automatización comprensiva de hechos?',['Repetición sin relaciones.','Construir hechos nuevos desde dobles, complementos, familias y propiedades.','Evitar toda práctica.','Usar solo calculadora.'],1],
    ['Interpretación','En 402 − 185 resta siempre el dígito menor del mayor. ¿Qué revela?',['Comprensión sólida de la resta.','Una regla mecánica que ignora desagrupación y valor posicional.','Dificultad de lectura.','Problema de estimación únicamente.'],1],
    ['Interpretación','Resuelve 99 + 36 como 100 + 36 − 1. ¿Cómo se interpreta?',['Error porque no usó algoritmo vertical.','Estrategia válida de compensación basada en equivalencia.','Adivinación.','Dificultad posicional.'],1],
    ['Aplicación','No recuerda 6 × 8, pero sabe 3 × 8. ¿Qué apoyo es pertinente?',['Memorizar sin explicación.','Duplicar 3 × 8 y explicar la relación multiplicativa.','Cambiar de tabla.','Sumar 6 + 8.'],1],
    ['Aplicación','¿Cómo enseñar la desagrupación en una resta?',['Decir “se pide prestado”.','Conectar material base diez, notación expandida y cada paso del algoritmo.','Practicar columnas sin material.','Invertir los dígitos.'],1],
    ['Aplicación','Un resultado de suma supera ampliamente una estimación razonable. ¿Qué debe hacer el estudiante?',['Aceptar el algoritmo.','Revisar el procedimiento usando estimación y operación inversa.','Borrar la estimación.','Repetir el resultado.'],1],
    ['Decisión pedagógica','Ante errores de cálculo heterogéneos, ¿qué decisión es más rigurosa?',['Aplicar la misma ficha.','Analizar significado, hechos, estrategia, valor posicional y control para focalizar el apoyo.','Entrenar solo velocidad.','Reducir el objetivo.'],1]
  ], problemSolving: [
    ['Comprensión conceptual','¿Qué distingue un problema de un ejercicio rutinario?',['El problema siempre tiene texto.','Exige construir una estrategia sin recibir directamente el procedimiento.','Usa números mayores.','Debe resolverse mentalmente.'],1],
    ['Comprensión conceptual','¿Qué función cumple modelar un problema?',['Subrayar palabras clave.','Representar las cantidades y relaciones para vincular la situación con lenguaje matemático.','Ejecutar el algoritmo.','Copiar el enunciado.'],1],
    ['Interpretación','Calcula bien, pero combina todos los números aunque uno sea irrelevante. ¿Dónde aparece el quiebre?',['En cálculo.','En comprensión y representación de la situación.','En hechos numéricos.','En escritura de dígitos.'],1],
    ['Interpretación','Resuelve correctamente al escuchar el enunciado segmentado, pero no al leerlo solo. ¿Qué debe analizarse?',['Solo capacidad matemática general.','La demanda lectora como interferencia y el razonamiento bajo ambas condiciones.','El algoritmo.','La memoria de tablas.'],1],
    ['Aplicación','Ante “Ana tiene 7 más que Luis”, ¿qué evita el uso mecánico de palabras clave?',['Sumar al ver “más”.','Construir una representación de ambas cantidades, la diferencia y la incógnita.','Borrar la palabra.','Practicar sumas.'],1],
    ['Aplicación','¿Cómo enseñar comprobación contextual?',['Repetir el cálculo.','Comparar la respuesta con una estimación, la pregunta y las condiciones de la situación.','Aceptar cualquier número.','Usar siempre calculadora.'],1],
    ['Aplicación','Un estudiante inicia operaciones sin explicar qué busca. ¿Qué apoyo es pertinente?',['Entregar la operación.','Pedir reformular la pregunta, identificar datos necesarios y anticipar un plan.','Aumentar la cantidad de ejercicios.','Corregir al final.'],1],
    ['Decisión pedagógica','Ante bajo desempeño en problemas, ¿qué decisión es más rigurosa?',['Entrenar cálculo a todos.','Evaluar por separado comprensión, representación, planificación, cálculo y comprobación para focalizar apoyo.','Reducir el lenguaje siempre.','Concluir DEA con una prueba.'],1]
  ], mathIntervention: [
    ['Comprensión conceptual','¿Qué debe incluir una línea base matemática útil?',['Solo porcentaje total.','Procedimientos, errores, representaciones, explicaciones y respuesta a apoyos.','Solo diagnóstico.','Cantidad de sesiones.'],1],
    ['Comprensión conceptual','¿Qué evidencia fidelidad de implementación?',['Que el apoyo se realizó con frecuencia, duración y procedimiento planificados.','Que el estudiante asistió.','Que se completaron fichas.','Que el resultado final fue bajo.'],0],
    ['Interpretación','Compara con material, pero no con numerales; nunca se enseñó el puente simbólico. ¿Qué indica?',['Falta de capacidad general.','La intervención no abordó explícitamente la transferencia entre representaciones.','Debe retirarse el material.','Se confirma DEA.'],1],
    ['Interpretación','Se planificaron cuatro sesiones, se realizó una y no hay medida de desempeño. ¿Qué procede?',['Concluir falta de respuesta.','Corregir fidelidad y establecer un indicador antes de juzgar eficacia.','Cambiar diagnóstico.','Suspender el apoyo.'],1],
    ['Aplicación','¿Cuál indicador mide mejor progreso en valor posicional?',['Fichas completadas.','Precisión y explicación al representar números equivalentes en tareas periódicas.','Asistencia.','Tiempo sentado.'],1],
    ['Aplicación','Progresa con bloques, pero depende del adulto para elegirlos. ¿Qué ajuste corresponde?',['Mantener todas las indicaciones.','Enseñar cuándo elegir la representación y retirar ayudas gradualmente.','Eliminar el material.','Reducir los números.'],1],
    ['Aplicación','No hay progreso pese a alta fidelidad. ¿Qué decisión es pertinente?',['Repetir indefinidamente.','Revisar hipótesis, método, intensidad y ampliar evidencia.','Responsabilizar al estudiante.','Retirar apoyos.'],1],
    ['Decisión pedagógica','¿Qué secuencia integra evaluación e intervención?',['Prueba, etiqueta y ficha.','Línea base, hipótesis, objetivo, enseñanza explícita, monitoreo de fidelidad y progreso, ajuste.','Actividad y calificación.','Derivación y espera.'],1]
  ], mathIntegration: [
    ['Comprensión conceptual','¿Qué procesos deben distinguirse ante un error matemático?',['Solo cálculo y memoria.','Sentido numérico, representación, cálculo y resolución.','Lectura y escritura únicamente.','Rapidez y atención.'],1,'Unidad 1'],
    ['Interpretación','Resuelve con bloques, pero falla al registrar símbolos. ¿Qué se analiza?',['Capacidad general.','Conexión entre representaciones y notación.','Solo conteo.','Comprensión verbal.'],1,'Unidad 1'],
    ['Aplicación','¿Qué procedimiento aporta más evidencia?',['Marcar correcto o incorrecto.','Pedir explicar, representar, resolver y comprobar bajo condiciones comparables.','Cronometrar.','Repetir la tarea.'],1,'Unidad 1'],
    ['Comprensión conceptual','El valor posicional expresa:',['La forma del numeral.','El valor del dígito según su posición en agrupaciones de base diez.','La velocidad de lectura.','El orden de copia.'],1,'Unidad 2'],
    ['Interpretación','Forma 304, pero escribe 34. ¿Qué vínculo falta?',['Conteo oral.','Función posicional del cero entre agrupación y notación.','Estimación.','Operación inversa.'],1,'Unidad 2'],
    ['Aplicación','¿Cómo ampliar flexibilidad con 53?',['Usar solo 50 + 3.','Construir y justificar descomposiciones equivalentes.','Memorizarlo.','Copiarlo.'],1,'Unidad 2'],
    ['Comprensión conceptual','Una estrategia de cálculo es:',['Un procedimiento flexible elegido desde relaciones numéricas.','Un algoritmo obligatorio.','Una adivinanza.','Una tabla memorizada.'],0,'Unidad 3'],
    ['Interpretación','Resuelve 99 + 36 como 100 + 36 − 1. ¿Qué usa?',['Un error.','Compensación y equivalencia.','Conteo uno a uno.','Algoritmo vertical.'],1,'Unidad 3'],
    ['Aplicación','¿Cómo comprobar 402 − 185?',['Aceptar el algoritmo.','Estimar y usar relación inversa, revisando valor posicional.','Repetir el resultado.','Contar dígitos.'],1,'Unidad 3'],
    ['Comprensión conceptual','Modelar un problema significa:',['Buscar palabra clave.','Representar cantidades y relaciones para vincular situación y lenguaje matemático.','Ejecutar cálculo.','Copiar datos.'],1,'Unidad 4'],
    ['Interpretación','Calcula bien, pero usa todos los datos. ¿Dónde está el quiebre?',['Hechos numéricos.','Comprensión y representación de la situación.','Algoritmo.','Valor posicional.'],1,'Unidad 4'],
    ['Aplicación','¿Qué evita decidir por “más”?',['Sumar siempre.','Representar cantidades, relación e incógnita antes de operar.','Subrayar la palabra.','Eliminar el texto.'],1,'Unidad 4'],
    ['Comprensión conceptual','¿Qué permite juzgar una intervención?',['Fichas completadas.','Línea base, indicador de progreso y fidelidad.','Diagnóstico.','Asistencia solamente.'],1,'Unidad 5'],
    ['Interpretación','No hay progreso y se realizó un cuarto del plan. ¿Qué procede?',['Concluir falta de respuesta.','Corregir fidelidad antes de juzgar eficacia.','Retirar apoyo.','Cambiar objetivo sin evidencia.'],1,'Unidad 5'],
    ['Decisión pedagógica','¿Qué secuencia integra mejor el módulo?',['Respuesta, etiqueta y ficha.','Patrón, proceso, hipótesis, enseñanza explícita, monitoreo y ajuste.','Prueba y derivación.','Algoritmo y repetición.'],1,'Unidad 5']
  ], diversifiedDesign: [
    ['Comprensión conceptual','¿Qué caracteriza la diversificación?',['Crear un currículo distinto para cada estudiante.','Anticipar diversidad y ofrecer alternativas manteniendo propósitos y expectativas.','Reducir siempre los objetivos.','Aplicar adecuaciones individuales primero.'],1],
    ['Comprensión conceptual','¿Qué debe definirse antes de variar una modalidad?',['La tecnología disponible.','El aprendizaje o constructo central que debe conservarse.','El diagnóstico.','La opción preferida del docente.'],1],
    ['Interpretación','El objetivo es explicar causalidad y se permite respuesta oral o escrita con igual criterio. ¿Qué ocurre?',['Se reduce el objetivo.','Se diversifica la expresión manteniendo el constructo.','Se elimina la evaluación.','Se aplica PACI.'],1],
    ['Interpretación','El objetivo es escribir un texto y se reemplaza por completo por un audio. ¿Cuál es el problema?',['Ninguno.','La alternativa elimina una parte central del aprendizaje evaluado.','El audio siempre es más difícil.','Falta una nota.'],1],
    ['Aplicación','Un texto extenso bloquea Ciencias y decodificar no es el objetivo. ¿Qué apoyo corresponde?',['Reducir el contenido científico.','Ofrecer acceso segmentado, audio y diagramas, manteniendo las relaciones científicas.','Eximir al estudiante.','Evaluar lectura.'],1],
    ['Aplicación','¿Qué opción favorece participación sin bajar expectativas?',['Una tarea paralela más fácil.','Elección entre apoyos y formas pertinentes de trabajo con criterios comunes.','Menos contenido automáticamente.','Observación pasiva.'],1],
    ['Aplicación','Una opción mejora desempeño, pero genera dependencia total. ¿Qué debe revisarse?',['Solo mantenerla.','Eficacia, autonomía y posibilidad de retirar ayudas gradualmente.','El diagnóstico.','La calificación.'],1],
    ['Decisión pedagógica','¿Qué secuencia es coherente con el Decreto 83?',['Adecuar OA antes de enseñar.','Diversificar, evaluar respuesta y considerar adecuaciones si es insuficiente.','Separar primero.','Usar diagnóstico como única decisión.'],1]
  ], explicitTeaching: [
    ['Comprensión conceptual','¿Qué caracteriza el modelado cognitivo?',['Mostrar solo la respuesta.','Hacer visible el razonamiento, las decisiones y la comprobación mediante pensamiento en voz alta.','Entregar una pauta.','Repetir la instrucción.'],1],
    ['Comprensión conceptual','¿Cuál es el propósito del andamiaje?',['Mantener ayuda permanente.','Permitir realizar un proceso y transferir gradualmente la responsabilidad.','Simplificar siempre el objetivo.','Evitar errores.'],1],
    ['Interpretación','Resuelve solo con una pauta y no decide qué pasos usar. ¿Qué ocurre?',['Autonomía consolidada.','Dependencia del andamio y falta de desvanecimiento.','Dificultad del objetivo.','Falta de evaluación.'],1],
    ['Interpretación','El adulto entrega respuesta tras cada pausa breve. ¿Qué problema genera?',['Demasiada práctica.','No ofrece tiempo ni evidencia del nivel de ayuda necesario.','Exceso de autonomía.','Poca explicación final.'],1],
    ['Aplicación','¿Cuál es la secuencia de responsabilidad gradual?',['Trabajo independiente y luego explicación.','Modelado, práctica guiada, cooperación estructurada e independencia.','Evaluación, modelo y tarea.','Pista permanente.'],1],
    ['Aplicación','¿Qué pista preserva mejor el razonamiento del estudiante?',['Entregar el primer paso completo.','Preguntar “¿qué necesitas averiguar primero y por qué?”.','Resolver el ejemplo.','Señalar la respuesta.'],1],
    ['Aplicación','Un estudiante ya ejecuta una estrategia con precisión. ¿Qué sigue?',['Mantener todas las ayudas.','Reducir apoyos y comprobar uso autónomo en tareas variadas.','Cambiar inmediatamente el objetivo.','Evitar nuevos contextos.'],1],
    ['Decisión pedagógica','¿Cómo elegir el nivel de ayuda?',['Por diagnóstico.','Usar la mínima ayuda efectiva, observar respuesta y ajustarla.','Aplicar el máximo apoyo.','Dar la misma pista a todos.'],1]
  ], practiceFeedback: [
    ['Comprensión conceptual','¿Qué caracteriza la práctica distribuida?',['Muchas repeticiones seguidas.','Oportunidades breves separadas en el tiempo con recuperación del aprendizaje.','Una evaluación final.','Tareas sin retroalimentación.'],1],
    ['Comprensión conceptual','¿Qué hace accionable una retroalimentación?',['Incluye una calificación.','Vincula evidencia y criterio con una acción para el siguiente intento.','Corrige todos los errores.','Se entrega al final del semestre.'],1],
    ['Interpretación','Resuelve veinte ejercicios iguales, pero falla cuando cambia el formato. ¿Qué falta?',['Más repetición idéntica.','Variación, discriminación de condiciones y transferencia.','Una nota.','Menos ejemplos.'],1],
    ['Interpretación','Recibe un texto marcado y lo archiva sin revisar. ¿Cuál es el problema?',['Poca corrección.','La retroalimentación no genera una acción ni un nuevo intento.','Demasiada autonomía.','Falta una rúbrica numérica.'],1],
    ['Aplicación','¿Cómo promover recuperación activa?',['Releer la explicación.','Pedir recordar y aplicar la estrategia antes de consultar el apoyo.','Copiar el ejemplo.','Mostrar la respuesta.'],1],
    ['Aplicación','¿Qué retroalimentación es más útil?',['Muy bien.','Tu representación es correcta; revisa la incógnita y vuelve a elegir la operación.','Incorrecto.','Debes concentrarte.'],1],
    ['Aplicación','¿Cómo enseñar autorregulación?',['Pedir independencia inmediata.','Modelar metas, autoindicaciones y comprobación, guiarlas y retirar ayudas.','Entregar una pauta permanente.','Evitar errores.'],1],
    ['Decisión pedagógica','¿Qué diseño favorece transferencia?',['Ejercicios idénticos agrupados.','Práctica distribuida y acumulativa con ejemplos variados, explicación y retroalimentación.','Solo evaluación final.','Repetición sin contraste.'],1]
  ], accessSupports: [
    ['Comprensión conceptual','¿Qué caracteriza un apoyo de acceso?',['Reduce objetivos.','Modifica la vía de acceso o respuesta conservando el aprendizaje esperado.','Se asigna por diagnóstico.','Es siempre tecnológico.'],1],
    ['Comprensión conceptual','¿Qué criterio debe orientar la selección de un recurso?',['Su novedad.','La barrera, el objetivo y el cambio observable que produce.','La preferencia adulta.','El precio.'],1],
    ['Interpretación','Se usa audio en Ciencias y decodificar no es el objetivo. ¿Qué ocurre?',['Se invalida siempre.','Se reduce una demanda accesoria manteniendo el contenido científico.','Se modifica el OA.','Se elimina toda lectura.'],1],
    ['Interpretación','Se usa calculadora cuando el objetivo es ejecutar división. ¿Cuál es el riesgo?',['Ninguno.','Sustituye el proceso central que debe demostrarse.','Aumenta la dificultad.','Evalúa lectura.'],1],
    ['Aplicación','Un apoyo mejora precisión, pero requiere indicación adulta constante. ¿Qué se revisa?',['Solo mantenerlo.','Entrenar uso autónomo y retirar ayudas gradualmente.','Cambiar diagnóstico.','Bajar el objetivo.'],1],
    ['Aplicación','Instrucciones públicas simplificadas estigmatizan. ¿Qué alternativa es mejor?',['Retirar el apoyo.','Ofrecer segmentación y pauta visual para el grupo, con verificación discreta.','Separar al estudiante.','Repetir más fuerte.'],1],
    ['Aplicación','¿Cómo comprobar pertinencia de un teclado como apoyo?',['Usarlo siempre.','Comparar producción, autonomía y acceso manteniendo criterios del objetivo.','Contar pulsaciones.','Preguntar solo si le gusta.'],1],
    ['Decisión pedagógica','¿Qué secuencia es más rigurosa?',['Elegir tecnología y luego buscar una barrera.','Identificar barrera y objetivo, seleccionar apoyo, enseñar su uso y monitorear eficacia y autonomía.','Aplicar igual apoyo por diagnóstico.','Mantenerlo permanentemente.'],1]
  ], diversifiedAssessment: [
    ['Comprensión conceptual','¿Qué caracteriza una evaluación diversificada?',['Cambia el objetivo para cada estudiante.','Ofrece vías pertinentes para evidenciar el aprendizaje conservando propósito y criterios esenciales.','Elimina toda exigencia.','Usa solo pruebas orales.'],1],
    ['Comprensión conceptual','¿Para qué se recoge evidencia durante la enseñanza?',['Solo para asignar una nota.','Para interpretar el aprendizaje y decidir próximos pasos pedagógicos.','Para confirmar diagnósticos.','Para completar registros.'],1],
    ['Interpretación','Dos estudiantes obtienen el mismo puntaje, pero muestran errores distintos. ¿Qué corresponde?',['Aplicar el mismo apoyo.','Analizar patrones por criterio y proceso para tomar decisiones diferenciadas.','Usar solo el promedio.','Repetir la prueba sin cambios.'],1],
    ['Interpretación','Una respuesta oral demuestra el concepto, pero leer no era parte del objetivo. ¿Qué indica?',['La evidencia es inválida.','La vía oral redujo una demanda accesoria y permitió observar el constructo.','Debe bajarse el criterio.','La lectura debe calificarse igualmente.'],1],
    ['Aplicación','Una pauta mejora el producto, pero mantiene dependencia adulta. ¿Qué decisión es pertinente?',['Mantenerla sin revisión.','Enseñar su uso, retirar ayudas gradualmente y monitorear autonomía.','Eliminar todo apoyo.','Reducir el objetivo.'],1],
    ['Aplicación','La mayoría falla el mismo criterio después de una explicación. ¿Qué acción aporta más?',['Calificar y avanzar.','Reenseñar con otra representación, práctica guiada y una comprobación breve.','Derivar al grupo.','Repetir idéntica prueba.'],1],
    ['Aplicación','¿Qué evidencia permite ajustar mejor una intervención?',['Solo el puntaje total.','Desempeño por criterio, tipo de error, ayuda requerida y cambio entre momentos.','La opinión aislada del adulto.','La cantidad de tareas.'],1],
    ['Decisión pedagógica','¿Cuál es el ciclo más coherente?',['Evaluar, calificar y archivar.','Precisar criterio, diversificar vías, recoger evidencia, interpretarla y ajustar enseñanza o apoyo.','Elegir formato según diagnóstico.','Cambiar el objetivo después de cada error.'],1]
  ], participationBelonging: [
    ['Comprensión conceptual','¿Qué diferencia participación de presencia?',['La ubicación en el aula.','El involucramiento significativo y la posibilidad de aportar e influir.','La cantidad de asistencia.','El diagnóstico.'],1],
    ['Comprensión conceptual','¿Qué caracteriza el sentido de pertenencia?',['Cumplir tareas en silencio.','Sentirse reconocido, seguro y valorado como integrante de la comunidad.','Recibir trabajo individual.','No necesitar apoyos.'],1],
    ['Interpretación','Un estudiante está en el grupo, pero siempre realiza una tarea paralela. ¿Qué indica?',['Inclusión plena.','Presencia física sin participación en el propósito común.','Autonomía suficiente.','Aprendizaje colaborativo.'],1],
    ['Interpretación','Una estudiante rechaza un apoyo que la expone frente al curso. ¿Cómo usar su opinión?',['Ignorarla porque el apoyo funciona.','Integrarla como evidencia para rediseñar modalidad, contexto o momento.','Retirar todo apoyo.','Cambiarla de curso.'],1],
    ['Aplicación','Un estudiante siempre reparte materiales, aunque quiere registrar datos. ¿Qué corresponde?',['Mantener el rol seguro.','Enseñar y apoyar el registro, ampliando roles y expectativas.','Excluirlo del grupo.','Dejar que observe.'],1],
    ['Aplicación','¿Qué indicador permite observar participación significativa?',['Solo asistencia.','Frecuencia y calidad de aportes, interacción, elección y progreso en el propósito compartido.','Cantidad de fichas.','Tiempo fuera del aula.'],1],
    ['Aplicación','Un apoyo individual mejora precisión, pero separa sistemáticamente al estudiante. ¿Qué se debe analizar?',['Solo la precisión.','Su efecto conjunto en aprendizaje, participación, autonomía y pertenencia.','Solo la preferencia adulta.','La duración del diagnóstico.'],1],
    ['Decisión pedagógica','¿Qué secuencia favorece una decisión inclusiva?',['Asignar un rol y observar asistencia.','Escuchar al estudiante, observar barreras y facilitadores, acordar un ajuste y monitorear participación, aprendizaje y pertenencia.','Aplicar el mismo apoyo por diagnóstico.','Priorizar siempre el trabajo separado.'],1]
  ], coTeaching: [
    ['Comprensión conceptual','¿Qué define la coenseñanza?',['Dos adultos presentes.','Responsabilidad compartida en planificación, enseñanza, evaluación y ajuste.','Un especialista que atiende diagnósticos.','Dividir el curso.'],1],
    ['Comprensión conceptual','¿Cómo se selecciona una modalidad?',['Por costumbre.','Según objetivo, barreras y evidencia requerida.','Por diagnóstico.','Usando siempre estaciones.'],1],
    ['Interpretación','Un docente dirige siempre y otro apoya al mismo subgrupo. ¿Qué riesgo existe?',['Liderazgo compartido.','Roles jerárquicos, estigma y responsabilidad fragmentada.','Exceso de modalidades.','Falta de pruebas.'],1],
    ['Interpretación','Ambos conducen explicaciones conectadas. ¿Qué modalidad es?',['Separada.','En equipo.','Individual.','Derivación.'],1],
    ['Aplicación','¿Cómo aumentar oportunidades de respuesta sobre el mismo objetivo?',['Un grupo observa.','Enseñanza paralela con grupos flexibles y criterios comunes.','Separar por diagnóstico.','Tareas no relacionadas.'],1],
    ['Aplicación','¿Cómo usar uno enseña y otro observa?',['Observar cualquier cosa.','Acordar indicadores, registrar y analizar para ajustar.','Mantener roles siempre.','Mirar solo conducta.'],1],
    ['Aplicación','Las estaciones no producen evidencia comparable. ¿Qué falta?',['Más materiales.','Propósito articulado, tareas coherentes e indicadores.','Más tiempo.','Grupos fijos.'],1],
    ['Decisión pedagógica','¿Qué secuencia expresa colaboración?',['Dividir estudiantes.','Co-planificar objetivo, roles y evidencia; coenseñar; analizar y ajustar juntos.','Improvisar.','Delegar al especialista.'],1]
  ], inclusiveClimate: [
    ['Comprensión conceptual','¿Qué caracteriza una convivencia inclusiva?',['Ausencia de conflictos.','Participación, cuidado, derechos y respuesta formativa a las barreras.','Sanciones idénticas.','Apoyos separados.'],1],
    ['Comprensión conceptual','¿Qué es estigmatización?',['Un apoyo pertinente.','Atribuir una marca desvalorizante que reduce identidad y participación.','Una norma común.','Una evaluación.'],1],
    ['Interpretación','Un estudiante deja de usar un apoyo por burlas. ¿Qué evidencia muestra?',['El apoyo era innecesario.','Una barrera relacional que afecta acceso y pertenencia.','Falta de esfuerzo.','Autonomía.'],1],
    ['Interpretación','Se sanciona una burla, pero continúa la exposición pública del apoyo. ¿Qué falta?',['Otra nota.','Modificar la condición que sostiene el estigma.','Retirar el apoyo.','Cambiar el objetivo.'],1],
    ['Aplicación','Dos estudiantes siempre quedan fuera al formar equipos. ¿Qué corresponde?',['Esperar elección espontánea.','Rediseñar agrupamiento, roles e indicadores de participación.','Trabajar solos.','Sancionar al curso sin diálogo.'],1],
    ['Aplicación','¿Qué respuesta protege a quien sufrió discriminación?',['Pedirle mediar inmediatamente.','Escuchar sin culpabilizar, detener el daño y acordar resguardos.','Exponer el caso públicamente.','Minimizarlo.'],1],
    ['Aplicación','¿Cómo evaluar un cambio de convivencia?',['Solo contar sanciones.','Combinar recurrencia, percepción de seguridad, participación y observación.','Medir asistencia.','Preguntar solo al adulto.'],1],
    ['Decisión pedagógica','¿Qué secuencia es más completa?',['Sancionar y cerrar.','Proteger, escuchar, analizar barreras, actuar formativamente y monitorear.','Retirar a quien fue afectado.','Aplicar la misma medida siempre.'],1]
  ], interdisciplinaryFollowup: [
    ['Comprensión conceptual','¿Qué caracteriza el seguimiento interdisciplinario?',['Acumular informes.','Integrar evidencia y acciones complementarias en una decisión común.','Delegar a un especialista.','Reunirse sin indicadores.'],1],
    ['Comprensión conceptual','¿Qué distingue impacto de actividad?',['La frecuencia.','El cambio observable en desempeño, participación o autonomía.','La duración de reunión.','El número de profesionales.'],1],
    ['Interpretación','Se registran sesiones, pero no cambios. ¿Qué falta?',['Más sesiones.','Indicadores de resultado bajo condiciones comparables.','Otro diagnóstico.','Un informe extenso.'],1],
    ['Interpretación','Dos fuentes muestran desempeños distintos. ¿Qué corresponde?',['Elegir la menor.','Analizar tareas, contextos y apoyos antes de concluir.','Promediar sin contexto.','Descartar una fuente.'],1],
    ['Aplicación','¿Qué completa un acuerdo monitoreable?',['Solo objetivo general.','Acción, responsable, contexto, indicador y fecha de revisión.','Diagnóstico y firma.','Lista de reuniones.'],1],
    ['Aplicación','Un apoyo mejora precisión, pero no autonomía. ¿Qué procede?',['Mantenerlo igual.','Rediseñar ayudas y monitorear retiro gradual.','Eliminar el objetivo.','Aumentar dependencia.'],1],
    ['Aplicación','Cada profesional trabaja una meta distinta. ¿Qué debe hacer el equipo?',['Mantener planes paralelos.','Priorizar una necesidad y articular aportes complementarios.','Elegir una profesión.','Agregar tareas.'],1],
    ['Decisión pedagógica','¿Qué ciclo es más riguroso?',['Informar y archivar.','Triangular, priorizar, acordar, implementar, monitorear y ajustar.','Derivar y esperar.','Mantener apoyos por costumbre.'],1]
  ], assessmentIntegration: [
    ['Comprensión conceptual','¿Qué hace integral a una evaluación?',['La cantidad de pruebas.','La articulación de fuentes, contextos y participantes para orientar apoyos.','La existencia de un diagnóstico.','El uso exclusivo de instrumentos formales.'],1,'Unidad 1'],
    ['Interpretación','Una familia describe fortalezas no observadas en la escuela. ¿Cómo se usa esa información?',['Se descarta.','Se integra y contrasta con otras fuentes y condiciones.','Reemplaza toda evaluación.','Solo confirma diagnósticos.'],1,'Unidad 1'],
    ['Aplicación','¿Qué decisión deriva mejor de una evaluación integral?',['Un apoyo genérico.','Una acción vinculada con evidencia, responsable e indicador.','Archivar el informe.','Aplicar la misma respuesta por diagnóstico.'],1,'Unidad 1'],
    ['Comprensión conceptual','¿Qué significa triangular evidencia?',['Promediar puntajes.','Contrastar fuentes, métodos y momentos.','Repetir una prueba.','Elegir el resultado menor.'],1,'Unidad 2'],
    ['Interpretación','El desempeño cambia al permitir respuesta oral. ¿Qué corresponde analizar?',['Solo la comprensión.','La demanda escrita como posible interferencia y el patrón bajo ambas condiciones.','El diagnóstico.','La nota final.'],1,'Unidad 2'],
    ['Aplicación','¿Qué interpretación es más rigurosa?',['No puede aprender.','Describe tarea, error, apoyo, cambio observado e hipótesis a contrastar.','Su DEA explica todo.','Rinde bajo.'],1,'Unidad 2'],
    ['Comprensión conceptual','¿Qué criterio es relevante para una posible DEA?',['Una dificultad aislada.','Persistencia significativa pese a medidas pedagógicas pertinentes.','Una nota insuficiente.','Preferir material visual.'],1,'Unidad 3'],
    ['Interpretación','Un grupo no recibió enseñanza sistemática y presenta bajo desempeño. ¿Qué se examina primero?',['DEA grupal.','Oportunidad y calidad de enseñanza, seguida de apoyo y monitoreo.','PACI para todos.','Solo prueba estandarizada.'],1,'Unidad 3'],
    ['Decisión pedagógica','Ante evidencia ambigua, ¿qué procede?',['Diagnosticar preventivamente.','Mantener apoyos y ampliar evaluación diferencial e interdisciplinaria.','Retirar apoyos.','Usar el dato más bajo.'],1,'Unidad 3'],
    ['Comprensión conceptual','¿Cuándo se requiere PACI dentro del PAI?',['Ante todo apoyo.','Cuando existen adecuaciones significativas a los OA.','Por cualquier ajuste de acceso.','Para toda DEA.'],1,'Unidad 4'],
    ['Interpretación','Dos sesiones semanales sin evidencia de cambio informan principalmente:',['Impacto.','Actividad realizada, pero no eficacia.','Autonomía.','Generalización.'],1,'Unidad 4'],
    ['Aplicación','¿Qué completa un plan monitoreable?',['Objetivo general y diagnóstico.','Prioridad, objetivo observable, acción, responsable, indicador y revisión.','Cantidad de informes.','Solo calendario.'],1,'Unidad 4'],
    ['Comprensión conceptual','¿Qué define colaboración efectiva?',['División profesional del estudiante.','Propósito común, roles complementarios y decisiones compartidas.','Más reuniones.','Especialista como único responsable.'],1,'Unidad 5'],
    ['Interpretación','La familia solo firma un plan ya decidido. ¿Qué falta?',['Otro formulario.','Participación auténtica.','Más tecnicismos.','Una prueba médica.'],1,'Unidad 5'],
    ['Aplicación','¿Cómo comunicar información sensible?',['Compartir todo con todo el personal.','Usar lenguaje comprensible y entregar por canales resguardados solo lo pertinente a cada rol.','Grupo abierto de mensajería.','Omitir apoyos.'],1,'Unidad 5']
  ]};
  const questions = questionSets[quiz.dataset.quiz || 'bio'];
  const letters=['A','B','C','D'];
  quiz.innerHTML=questions.map((x,i)=>`<fieldset class="quiz-question"><legend><span>${i+1} de ${questions.length} · ${x[0]}${x[4] ? ` · ${x[4]}` : ''}</span>${x[1]}</legend>${x[2].map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"><span><strong>${letters[j]}</strong>${o}</span></label>`).join('')}</fieldset>`).join('')+'<p class="quiz-error" role="alert" tabindex="-1" hidden>Responde todas las preguntas antes de finalizar.</p><button class="button green-button quiz-submit">Ver mi resultado</button>';
  quiz.addEventListener('submit',(event)=>{event.preventDefault();const data=new FormData(quiz);if(questions.some((_,i)=>!data.has(`q${i}`))){const e=quiz.querySelector('.quiz-error');e.hidden=false;e.focus();return;}let total=0;const stats={},units={};questions.forEach((x,i)=>{const ok=Number(data.get(`q${i}`))===x[3];total+=ok;stats[x[0]]??={correct:0,total:0};stats[x[0]].total++;stats[x[0]].correct+=ok;if(x[4]){units[x[4]]??={correct:0,total:0};units[x[4]].total++;units[x[4]].correct+=ok;}});const sorted=Object.entries(stats).sort((a,b)=>b[1].correct/b[1].total-a[1].correct/a[1].total);document.querySelector('#result-percent').textContent=`${Math.round(total/questions.length*100)}%`;document.querySelector('#result-score').textContent=`${total} de ${questions.length}`;document.querySelector('#result-strength').textContent=sorted[0][0].toLowerCase();document.querySelector('#result-improve').textContent=sorted.at(-1)[0].toLowerCase();const bars=(source)=>Object.entries(source).map(([n,v])=>{const p=Math.round(v.correct/v.total*100);return `<article><div><strong>${n}</strong><span>${v.correct}/${v.total} · ${p}%</span></div><div class="mini-progress green" role="progressbar" aria-label="${n}: ${p} por ciento"><span style="width:${p}%"></span></div></article>`}).join('');document.querySelector('#skill-breakdown').innerHTML=bars(stats);const unitBreakdown=document.querySelector('#unit-breakdown');if(unitBreakdown)unitBreakdown.innerHTML=bars(units);const result=document.querySelector('#resultado');result.hidden=false;result.scrollIntoView({behavior:'smooth'});result.querySelector('h2').focus({preventScroll:true});});
  document.querySelector('#retry-quiz').addEventListener('click',()=>{quiz.reset();document.querySelector('#resultado').hidden=true;quiz.querySelector('.quiz-error').hidden=true;document.querySelector('#practica').scrollIntoView({behavior:'smooth'});});
});
